### DISCUSSION TITLE
Should Parser Validate the Entire TOML File Before Returning the Found Queried Value?

### DISCUSSION THREAD

**Discussion by hollowaykeanho** [toml-lang/toml#1035] [Q&A] [answered]
Hi, say the parser already found a queried value by a given key half-way parsing the TOML file, should the parser continues to validate the entire toml file's validity or can it return early? Please consider both small and very large file (e.g. TB sized).

Let's assume somewhere is the last quarter of the TOML file is both valid and invalid.

CONTEXT:

I'm asking to for comparing with other data types like JSON where the full file validation is strictly required. Hence, JSON is not a suitable data spec for large file.

TOML specification did not specify this requirement (https://toml.io/en/v1.0.0#objectives). Currently writing a parser library for POSIX compliant shell script using 1.0.0 spec.

The reason I'm asking for both small and very large file is mainly to develop an adaptable and scalable algorithm.

**Comment by ChristianSi** [comment]
I'd say for that specific use case there's no reason for the parser to read and validate the rest of the file. At least I don't think there's anything in the spec that says so.

**Reply by hollowaykeanho** [reply]
Hmm, will be it becomes an official spec somewhere down the future? I'm planning to pass in an optional option with default to bail early mode.

**Reply by eksortso** [reply, marked as answer]
We never took text streams into account when defining the standard, which wasn't intended to be a data serialization format. That would be nice, but we never considered it. It's not a common configuration use case.

There's a remote possibility that a table or key will be defined more than once on a stream, which would invalidate the complete TOML text. Like so:

```toml
[example]
item = "value"
# Imagine the stream is cut off at this point.
item = "other value"  # INVALID, since the key example.item was defined already.
```

Or like so:

```toml
[example]
item = "value"
# Imagine the stream is cut off at this point.

[example]  # INVALID, since the table "example" was defined already.
```

Since the stream parser could not guarantee against duplicate definitions and would implicitly favor the first definition found, then the parser would technically be non-compliant.
