### DISCUSSION TITLE
Discussing nulls again, sorry

### DISCUSSION THREAD

**Discussion by fizmat** [toml-lang/toml#1037] [General]
Just bumped into this limitation in real life, specifically with a list containing nulls

`pyproject.toml`:
```toml
[tool.cxfreeze.bdist_msi.data]
Shortcut = ["MainShortcut", "DesktopFolder", "start_my_app", None, None, None, None, None, None, None, None, None]
```

"" or {} don't work, they are interpreted as a string/dictionary, not None. This expects exactly 12 values to insert one record into a ?sql? table where all columns except the first one are nullable.

I know the perfect fix would be to improve support of `pyproject.toml` in cx_Freeze. (As opposed to older `setup.py`, which obviously can create tuples with Nones easily). Ideally they should probably represent records in msi tables as a dictionaries and not tuples in the first place. But I can see why they went with the easiest implementation for the niche use-case of creating MSI installers, especially as setup.py was the only way to configure projects, so toml limitations were not even on the horison.

But having absolutely no way to represent None/null is still very annoying.
