### ISSUE TITLE
Alternative syntax for strings / empty tables

### ISSUE THREAD

**Issue by sergei-mironov** [toml-lang/toml#1018]
Hi. Let me propose an alternative simplified syntax for strings or empty tables. The following TOML code is currently considered invalid

``` toml
[table.list]
String1
String2
```

The proposal is to make it equal to one or all of the following valid toml expressions:

``` toml
[table.list]
String1 = {}
String2 = {}
```

``` toml
[[table.list.String1]]
[[table.list.String2]]
```

``` toml
[table]
list = ["String1", "String2"]
```

What do you think?

**Comment by arp242** [comment]
This would complicate parsing and error reporting quite a bit for what seems like minimal benefit.

It's also not very "obvious"; you give three quite different possible meanings of "String1" here. So I wouldn't be a fan based on that either.

**Comment by eksortso** [comment]
@grwlf It seems as if you wish to fulfil a particular need with your proposed syntax. But you're not making it clear what need you want to fulfil. Maybe we're missing something that's obvious to you.

Could you provide some further details, so we can tell where you're coming from? What's your use case (or use cases) that would benefit from the syntax? What can't we do with the current syntax?

**Comment by grwlf** [comment]
@eksortso @ChristianSi thank you for the response. Yes, indeed - my proposal is motivated by a particular need that we experienced. I would formulate it as follows:
* To remove boilerplate `{}`  in configurations which have the following form:
  ``` toml
  [config.section]
  A = {}
  Lot = {}
  Of = {}
  Items = { where = "most of items are empty, only few have some parameters" }
  ``` 
* In Python, to get the corresponding dictionary as `dict[str, dict[str, str]]` mapping items to their key-value parameters (which would be mostly empty).

 Toml lib's internal representation is not really important. This is why I wrote `any or all`: any representation which we can interpret as the above `dict[..]` would work.
