### ISSUE TITLE
Clarify whether whitespace is permissible between the brackets in headers of table arrays

### ISSUE THREAD

**Issue by dmbaturin** [toml-lang/toml#1024]
The spec says that this is a valid array of tables:

```toml
[[lots_of_tables]]
  foo = 1
  bar = 2
```

It doesn't say whether this is an invalid array of tables:

```toml
[ [ lots_of_tables ] ]
  foo = 1
  bar = 2
```

The ABNF grammar file does suggest that it's an inseparable token, but it would be nice to have a verbal note in the spec as well, like:

```
The double bracket is an inseparable token, and attempts to insert whitespace between the brackets (`[ [` or `] ]`) will cause prase errors.
```
