### ISSUE TITLE
No way to go back to global

### ISSUE THREAD

**Issue by espadrine** [toml-lang/toml#107]
While trying to see how I would write some of the [json I have lying around](https://github.com/espadrine/set/blob/master/package.json),
I noticed that one restriction that TOML has is that it doesn't allow
to go back to the global hash.

``` toml
name = "dotset"
version = "2013.02.24"

[engines]
node = ">=0.4.0"
[scripts]
test = "node js/test"
# You don't want the following key to be part of "scripts"
main = "js/set.js"
```

Obviously, we can move it back to the start of the document,
but that breaks the promise that you can move things around
(which is the reason we don't have `[.nested-keygroup]`).
Also, it means that we cannot put related elements together
unless they're both one level deep.

Proposal: use `[]`.

``` toml
name = "dotset"
version = "2013.02.24"

[engines]
node = ">=0.4.0"
[scripts]
test = "node js/test"
# You don't want the following key to be part of "scripts"
[]
main = "js/set.js"
```
