### ISSUE TITLE
[RFC] address hash key and value in one line

### ISSUE THREAD

**Issue by liuggio** [toml-lang/toml#127]
Hi, in order to be simple as possible this RFC will add a little of ambiguousness

I think this valid toml is too difficult to read

``` toml
[database.ports]
primitive = "Array"
required = true

    [database.ports.range]    
    min = 0

    [database.ports.content]
    primitive = "Integer"

    [database.ports.content.range]
    min = 1024
    max = 49151
```

so I propose this:

``` toml
[database.ports]
primitive = "Array"
required = true
range.min = 0
content.primitive = "Integer"
content.range.min = 1024
content.range.max = 49151
```

The file is not a valid `toml` file because:
- I defined a key and its value in a single line.
- I handled a keygroup as a normal key and I omitted the full path.

:+1:  for me of course.
