### ISSUE TITLE
Use colons instead, or in addition to equals.

### ISSUE THREAD

**Issue by ianstormtaylor** [toml-lang/toml#161]
Colons are much less visually distracting and easier to type being on the home row. I think this is something YAML/JSON/Javascript/Python got right.

If you look at the two examples below, the first one is much noisier:

``` toml
# This is a TOML document. Boom.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
organization = "GitHub"
bio = "GitHub Cofounder & CEO\nLikes tater tots and beer."
dob = 1979-05-27T07:32:00Z # First class dates? Why not?

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
```

``` toml
# This is a TOML document. Boom.

title: "TOML Example"

[owner]
name: "Tom Preston-Werner"
organization: "GitHub"
bio: "GitHub Cofounder & CEO\nLikes tater tots and beer."
dob: 1979-05-27T07:32:00Z # First class dates? Why not?

[database]
server: "192.168.1.1"
ports: [ 8001, 8001, 8002 ]
connection_max: 5000
enabled: true
```

I could also get behind making them interchangeable, for preference. Don't know if that offends you or not though :p

PS. Cool that the syntax highlighting already worked :) it must be a sign.
