### ISSUE TITLE
: instead of [,] and =

### ISSUE THREAD

**Issue by mathusiast** [toml-lang/toml#19]
```
    [owner]
    name = "Tom Preston-Werner"
    organization = "GitHub"
    bio = "GitHub Cofounder & CEO\nLikes tater tots and beer."
    dob = 1979-05-27T07:32:00Z # First class dates? Why not?
```

why not

```
    owner:
    name: "Tom Preston-Werner"
    organization:  "GitHub"
    bio: "GitHub Cofounder & CEO\nLikes tater tots and beer."
    dob: 1979-05-27T07:32:00Z # First class dates? Why not?
```
