### ISSUE TITLE
Support quoted "." in table header

### ISSUE THREAD

**Issue by owenthereal** [toml-lang/toml#212]
"." is reserved for table header to express nested tables but it'd be nice to support quoted "." as valid table header names so that things like host name can be expressed in table header.

We're trying to [use host name as the table header](https://github.com/github/hub/pull/515#issuecomment-37144023) like this:

``` toml
[host."github.com"]
user = "jingweno"
oauth_token = "OTOKEN"
api_protocol = "http"
git_protocol = "git"
```

But "." is treated as a separator for nested tables even it's quoted. It'd make sense to extend the current spec to treat quoted "." as valid table header name.
