### ISSUE TITLE
A Proposal for Keys

### ISSUE THREAD

**Issue by wycats** [toml-lang/toml#220]
This is related to #65, #67, #185, #90, #180, #62, #126, #83, and probably others.

# Motivation

The TL;DR is that keys are currently slightly ambiguous, but also don't support a number of commonly desired characters.

A couple of examples:

```toml
[ips.127.0.0.1]
[directories.Space Separated]
```

In Cargo, this comes up because we use dependency names as keys:

```toml
[dependencies]

hammer.rs = "1.0.0"

# or

[dependencies.hammer.rs] = "1.0.0"
```

# Proposal

* Unadorned keys are one or more [alphabetic](http://www.unicode.org/reports/tr44/#Alphabetic), [numeric value](http://www.unicode.org/reports/tr44/#Numeric_Value), `-`, `_`, `$`, `!` or `?` characters.
* Quoted keys are valid [Toml Strings](https://github.com/toml-lang/toml#string).

So this would be valid:

```toml
[dependencies]

"hammer.rs" = "1.0.0"

# or

[dependencies."hammer.rs"] = "1.0.0"
```

I know there have been many discussions on this topic before. I have read them and have tried to include their considerations in this proposal.

One note: I think including `-` as a valid unadorned identifier character is extremely important.
