### ISSUE TITLE
Notation for Relative Tables

### ISSUE THREAD

**Issue by trans** [toml-lang/toml#229]
Seems like one of those _obvious_ things. Exact notation to be determined, but I'll throw out the one that comes to my mind first:

``` toml
[servers] {
  [alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [beta]
  ip = "10.0.0.2"
  dc = "eqdc10"
}
```
