### ISSUE TITLE
Do the definitions of the same table array need to follow each other?

### ISSUE THREAD

**Issue by cies** [toml-lang/toml#252]
I raised quite a number of issues in a short time, this is because I want to be sure how to implement a Toml parser in Haskell. I improve upon the current one `toml` which is not very compliant, and lacks tests.

So one more issue.  Is the following allowed?

``` toml
[[product]]
price = 9.99

[[employee]]
name = "Marinus van der Lubbe"

[[product]]
type = "ZX80"
```

It would considerably complicate parsing for me to support this.  And given the structural similarity that TOML should have with JSON (I think this would be impossible in JSON), I think this should be explicitly forbidden by the spec.
