### ISSUE TITLE
tests/example.toml does not parse

### ISSUE THREAD

**Issue by cies** [toml-lang/toml#254]
The spec says:

``` toml
# DO NOT DO THIS EITHER

[a]
b = 1

[a.b]
c = 2
```

Yet `example.toml` contains:

``` toml
[servers]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.alpha]
```

My parser currently rejects `example.toml` as valid TOML.

Is that correct?

Or is indentation important after all?
