### ISSUE TITLE
Keys after tables

### ISSUE THREAD

**Issue by matthewmueller** [toml-lang/toml#272]
Probably missing something, but it seems strange to me that the following:

``` toml
[[tasks]]
  title = "Implement Off Canvas jQuery Plugin"
  price = 50
  id = "12345"
  bids = 7

  [tasks.author]
    avatar = "https://secure.gravatar.com/avatar/5ff865d011ef4dcc982b82f7d28112c7"
    name = "Brian"
    location = "San Francisco"

  description = "some description"
```

Would put `description` inside `tasks.author`. It basically enforces that keys must be before tables. Is there a better way to represent this?
