### ISSUE TITLE
Nested arrays of tables

### ISSUE THREAD

**Issue by yasammez** [toml-lang/toml#353]
Hi everyone!

TOML has arrays:

``` toml
array = [ [1, 0], [0, 1] ]
```

``` json
"array":[ [ 1, 0], [0, 1] ]
```

TOML has tables:

``` toml
[table]
value = 1
```

``` json
"table":{ "value":1 }
```

TOML even has arraytables:

``` toml
[[arraytable]]
value = 1
[[arraytable]]
value = 2
```

``` json
"arraytable":[ { "value":1 }, { "value":2} ]
```

But is there any way to do something like

``` json
"nested_array_table":[ 
  [ { "value":1 }, {"value":0} ], 
  [ {"value":0}, {"value":1, "comment":"bottom right diagonal element"} ] ]
```

in TOML? If so, how can I do this? If not, why can't I do this?

I understand that there is always a way around this, by for instance flattening arrays

``` toml
[[matrix]]
value = 1
[[matrix]]
value = 0
[[matrix]]
value = 1
[[matrix]]
value = 0
comment = "bottom right diagonal element"
```

or introducing _filler_ structs:

``` toml
[[matrix.row]]
  [[matrix.row.column]]
  value = 1
  [[matrix.row.column]]
  value = 0
[[matrix.row]]
  [[matrix.row.column]]
  value = 1
  [[matrix.row.column]]
  value = 0
  comment = "bottom right diagonal element"
```

However, none of these seems really appropriate. Also, in that case, TOML would be strict less expressive than JSON, which is kind of a pitty, since JSON is so darn unreadable.

**Comment by fischmax** [comment]
One possible idea for an extension, which, I admit, scales not very well, would be to add additional layers of brackets around the table names: one for each level of array depth:

```toml
[[[matrix]]]
value = 1
[[matrix]]
value = 0
[[[matrix]]]
value = 0
[[matrix]]
value = 1
comment = "bottom right diagonal element"
```
This would be equivalent to the following JSON:

```json
"matrix":[ [ { "value":1 }, { "value":0 } ], [ { "value":0 }, { "value":1, "comment":"bottom right diagonal element" } ] ]
```

**Comment by sanmai-NL** [comment]
Why does the lack of a matrix notation make TOML strictly less expressive than JSON? I'm interested to know, since I'm not aware of any such notation in JSON.

**Comment by ChristianSi** [comment]
@fischmax: TOML has inline tables, so you should be able to write your example as follows (I think):

    nested_array_table = [ 
        [ {value = 1}, {value  = 0} ], 
        [ {value = 0}, {value = 1, comment = bottom right diagonal element} ] ]

**Comment by franklinyu** [comment]
In #309 @jodastephen suggested an alternative grammar for array table:

```toml
[analyzers.filter]
  [#]
  type = "icu-tokenizer"

  [#]
  type = "lowercase"

  [#]
  type = "length"
  min = 2
  max = 35
```

If this is accepted, it can be easily extended to allow n-dimension matrix:

```toml
[nested_array_table]
  [#]
    [##]
    value = 1
    [##]
    value = 0

  [#]
    [##]
    value = 0
    [##]
    value = 1
    comment = "bottom right diagonal element"
```
