### ISSUE TITLE
Allow single-quoted strings as keys

### ISSUE THREAD

**Issue by lfairy** [toml-lang/toml#354]
The following constructs don't work:

```toml
[foo.'bar']
# ...
```

```toml
[foo]
'bar' = 42
```

But this does:

```toml
[foo]
bar = 'baz'
```

Since key names look a lot like strings, I think it'd be more consistent if they accepted the full string syntax.
