### ISSUE TITLE
Example. Drupal library declaration

### ISSUE THREAD

**Issue by dcorb** [toml-lang/toml#365]
This is a support request.

We are evaluating to use TOML in Drupal as an optional alternative to YAML for declaring structure of data, for example libraries.yml files

https://www.drupal.org/node/2422141

I got quite confused with the use of "."s but after reading this recent PR, I understood better https://github.com/toml-lang/toml/pull/283

Is this an equivalent declaration ? 
YAML
````
backbone:
  remote: https://github.com/jashkenas/backbone
  version: "1.2.3"
  license:
    name: MIT
    url: https://github.com/jashkenas/backbone/blob/1.2.3/LICENSE
    gpl-compatible: true
  js:
    assets/vendor/backbone/backbone-min.js: { weight: -19, minified: true }
  dependencies:
    - core/underscore

````

Is this the simplest way to write it as TOML? How can I add "backbone.dependencies" to keep the same order as YAML ?

TOML. 
````
[backbone]
  remote = "https://github.com/jashkenas/backbone"
  version = "1.2.3"
  dependencies = ["core/underscore"]

  [backbone.license]
  name = "MIT"
  url = "https://github.com/jashkenas/backbone/blob/1.2.3/LICENSE"
  gpl-compatible = true

  [backbone.js."assets/vendor/backbone/backbone-min.js"] 
  minified = true
  weight = -19
````
