### ISSUE TITLE
Are these allowed by the Spec ?

### ISSUE THREAD

**Issue by kezhuw** [toml-lang/toml#379]
I am trying to write an v0.4.0 compatible toml library in Go. I am reading the Spec with caution, and this results in some cases that may not directly specified in Spec. Here I list these, and expect feedbacks.

1) Spec says:
> All table names and keys must be non-empty.
```toml
# NOT VALID TOML
[]
[a.]
[a..b]
[.b]
[.]
 = "no key name" # not allowed
```

But it does not specify whether following is ok or not ? At least, I found it is ok in [BurntSushi/toml][]
```toml
[""]

[super."".sub]
```

2) Since we can define array in two forms, so I can write following. Is it ok or not ? 
```toml
servers = []
[[servers]]
port = 1234

# another toml file
locals = [ { net = "ip4", port = 1234 }, { port = 5678 } ]
[[locals]]
net = "ip4"
port = 2345
```

3) Spec says that:
> Data types may not be mixed in array.

```toml
[[servers]]
port = 1234

[[servers]]
port = "2346"  # Does this conflict with `port = 1234` ?
```

4) From Spec:
> Each double-bracketed sub-table will belong to the most recently defined table element above it.
> ```toml
> [[fruit]]
>   name = "apple"
>
>   [fruit.physical]
>     color = "red"
>     shape = "round"
>
>   [[fruit.variety]]
>     name = "red delicious"
>
>   [[fruit.variety]]
>     name = "granny smith"
> 
> [[fruit]]
>   name = "banana"
>
>   [[fruit.variety]]
>     name = "plantain"
> ```

What "above" means ? File position or super-sub relationship ?
```toml
[[array1]]
[[array2]]
[array1.subTable]  # subTable should be defined in `array1[0]` ? Or report an error ?
```

I am not a native english gay. There may be misunderstandings, please forgive it.

[BurntSushi/toml]: https://github.com/BurntSushi/toml
