### ISSUE TITLE
First-class list

### ISSUE THREAD

**Issue by chillum** [toml-lang/toml#391]
The common use case for using YAML is something like:
```yaml
- one: two
  two: one
- two: three
- one: three
```

or in JSON:
```json
[
  {"one": "two", "two": "one"},
  {"two": "three"},
  {"one": "three"}
]
```
That is, that is a first-class list. That's the thing, that's not present in TOML. One could make a structure like:
```toml
[[i]]
one = "two"
two = "one"
[[i]]
two = "three"
[[i]]
one = "three"
```

But that's note a first-class list. The first-class list notation is very popular in application config files, for example see [Ansible](https://github.com/leucos/ansible-tuto/blob/master/step-12/roles/apache/tasks/main.yml). I agree that TOML-way is more explicit, but there are many structures in the world that would benefit from a first-class list in terms of ease and convenience.
