### ISSUE TITLE
Terminate command after table

### ISSUE THREAD

**Issue by arxeiss** [toml-lang/toml#394]
I have file in TOML simmilar to this one
```TOML
dog = 1
cat = "invisible"

[food.a]
  price = 123
[food.b]
  price = 456

# Here it would be nice put terminate command

url = "http://www.google.com"
```

For priority reason I put some settings (here url) to the end of my config file. But parser put `url` as part of `food.b`. It would be nice to have opportunity to tell parser "Here table/array of tables ends", something like `pass` in Python.

I would prefer strict indentation, but indentation doesn't affect TOML since v0.1, now it would be stupid to change it. So only solution to me seems that one with alternative to Python `pass`

**Comment by BurntSushi** [comment]
Could you explain the expected behavior? Do you want `url` to be a top-level key? If so, what's wrong with putting it with the other top-level keys `dog` and `cat`?

I'm generally not a fan, since keys in tables are always in a very predictable location. With your suggestion, you might also be able to do:

```toml
[a]
foo = 1
[a.b]
bar = 2
pass
baz = 3
```

Where `foo` and `baz` are keys on table `a`. Yuck.

**Comment by arxeiss** [comment]
Yes, I thought about it as you described, be top level key. 

Reason is because of priority. Settings in tables is more important in my config file. So I wanted keep them in beginning of file. And those not so important settings and barely changed put to the bottom of file.

**Comment by stylemistake** [comment]
@BurntSushi
```
[a]
foo = 1
[a.b]
bar = 2
[/a.b]
[/a]
baz = 3
```
P.S. Just kidding. :)
If settings are not important, put them in a table in the end of config file. Top level is for *important* stuff.

**Comment by mojombo** [comment]
Yeah, I like the current system. Agreed with @stylemistake that if you have unimportant settings in top-level, you should move them into a table (which is what I, as a user, would expect anyhow).

**Comment by guai** [comment]
How about
```toml
[a]
foo=1
bar=2
[] #reopen toplevel section
toplevelkey = "value"
```
?
and since we haven't put any key to toplevel section before table `[a]` it seems to me consisten with other toml rules
