### ISSUE TITLE
Why `=` instead of `:`?

### ISSUE THREAD

**Issue by chillum** [toml-lang/toml#402]
Compare following structures:

```yaml
a: b
```

```json
{"a": "b"}
```

```toml
a = "b"
```

It's clear that TOML is using `=` for compatibility with INI format, but `:` seems more standard nowdays and is arguably more readable and easier to write.

Maybe TOML should switch to colon syntax before 1.0? Or this is really a taste issue and it should be closed?

**Comment by chillum** [comment]
Consider these examples. Isn't the semicolon more elegant?
```toml
web   = "https://ya.ru"
name  = "Yandex"
match = "Найти" # Regexp to match in response.
tries = 3       # Optional attempts number.
```

```json
{
  "web"   : "https://ya.ru",
  "name"  : "Yandex",
  "match" : "Найти",
  "tries" : 3
}
```

**Comment by chillum** [comment]
It TOML switched to colons, it could look like this:
```yaml
web   : "https://ya.ru"
name  : "Yandex"
match : "Найти" # Regexp to match in response.
tries : 3       # Optional attempts number.
```
