### ISSUE TITLE
Reference/circular ideas

### ISSUE THREAD

**Issue by viperscape** [toml-lang/toml#434]
There might not be enough use cases for this, but an idea I had was reference keys

##### Referencing in toml #####

```toml
[some.thing]
x = 1

[other]
y = @some.thing.x
```

results when parsed

```other.y = 1```  

##### Reasons #####

This could be beneficial to a sort of logic in configurations, similar to how css handles ```@media``` queries or for when you want to write something once and reference multiple times

Other examples:
```toml
[server.ip]
local = "0.0.0.0"
public = "192.168.1.1"

[host.local]
ip = @server.ip.local
port = 1234

[host.public]
ip = @server.ip.public
port = 80
```

In some language I could write
```
if (arg[0] == 'localhost') { listen( parsed_toml('host.local') ) }
```
