### ISSUE TITLE
Nested array tables with new intermediate table?

### ISSUE THREAD

**Issue by jgallagher** [toml-lang/toml#450]
Is this allowed?

```toml
[[a]]

[[a.b.c]]
foo = "bar"
```

If so, is this the correct representation (`b` is a non-array table)?

```json
{
  "a": [
    {
      "b": {
        "c": [
          { "foo": "bar" }
        ]
      }
    }
  ]
}
```
