### ISSUE TITLE
Global keys defined below array of tables

### ISSUE THREAD

**Issue by bartekn** [toml-lang/toml#453]
Consider the following toml:
```toml
[[song]]
name = "Thunder Road"
duration = "4m49s"

[[song]]
name = "Stairway to Heaven"
duration = "8m03s"

another = "value"
```
The specification isn't clear if `another` should be a part of `song` or a global value. [tomlv](https://github.com/BurntSushi/toml/tree/master/cmd/tomlv) from Validators section in the README file returns the following result:
```
song               ArrayHash
    song.name      String
    song.duration  String
song               ArrayHash
    song.name      String
    song.duration  String
    song.another   String
```
I think the specification should be updated with either:
* Allowing setting global values after array of tables (after a blank line) or
* Explicitly specifying that every `key = value` line (even after a blank line) will be considered a key the preceding array.
