### ISSUE TITLE
Indentation does not mix well with directly entering arbitrarily nested tables

### ISSUE THREAD

**Issue by scooter-dangle** [toml-lang/toml#466]
The current TOML spec ([v0.4.0](https://github.com/toml-lang/toml/blob/709e9e9ee91ba3c10f8613241b1497349803f4f4/README.md)) says that "indentation (tabs and/or spaces) is allowed but not required".

The spec gives an example of indenting where a table's non-table contents are indented at the same level as the table, but nested tables (and the nested tables' contents) are indented one level. E.g.,

```toml
[a]
data = 8
  [a.b]
  data = 17
```

In indented TOML in the wild, I've often seen the tables' non-tabular contents also indented an additional level, e.g.:

```toml
[a]
  data = 8
  [a.b]
    data = 17
```

In describing the issue, I'll use the former indentation style, but the issue applies to both styles.

The issue is that, when directly entering a deeply nested table without first declaring the parent tables, indented TOML can be both unintuitive and deceptive, which hinders it in its objective of being easy to read.

Examples
--------

### Example 1
Incorrectly(?) indented, it visually appears that `a.b` and `z` are at the same level of nesting from the root of the table, which is incorrect:
```toml
data = 8

[a.b]
data = 17

[z]
data = 3
  [z.b]
  data = 9
```

However, indenting `a.b` to the correct level is unintuitive. Without its enclosing parent, `a`, it hangs on its own out to the right:

```toml
data = 8

  [a.b]
  data = 17

[z]
data = 3
  [z.b]
  data = 9
```

This is sorely exacerbated when the level of nesting increases, and it becomes an article of faith on the part of the reader that the text is in the correct vertical column:

```toml
data = 8

      [a.b.a.a]
      data = 17

[z]
data = 3
      [z.b.a.a]
      data = 9
```

### Example 2
With the first kind of indentation (i.e., indenting only to show nestedness—not to show the full depth of nesting), grandchildren tables of table `a` appear to be immediate children:

```toml
[a]
data = 9
  [a.b.a]
  data = 17
  [a.d.b]
  data = 17
```

Even with indentation that fully reflects the depth of nesting, the reader still has to ignore the first impression that the two nested tables are direct siblings and notice that they actually have different parents within `a`.

```toml
[a]
data = 9
    [a.b.a]
    data = 17
    [a.d.b]
    data = 17
```

The solution to the above issues is to either encourage or require explicitly introducing all intervening tables when indenting TOML (or, perhaps, in general). Doing so more immediately illustrates to the reader the relationship between the two descendant tables as well as their relationship to `a` without the reader having to parse and compare every table declaration.

```toml
[a]
data = 9
  [a.b]
    [a.b.a]
    data = 17
  [a.d]
    [a.d.b]
    data = 17
```

If explicitly introducing all intervening tables from the root to the most nested table is not required, then indentation should be disallowed so that the reader is forced to always determine nesting directly by the bracketed table lines. Some may find this more difficult to read, but it allows for a more succinct (linewise, at least) TOML style while not communicating potentially inaccurate information about the structure of the table.

```toml
[a]
data = 9
[a.b.a]
data = 17
[a.d.b]
data = 17
```

### Example 3
Note: An even more deceptive case occurs when re-visiting a previously visited node:

```toml
[a]
data = 9
  [a.a]
  data = 17
  [a.b]
  data = 17
[z]
data = 4
  [z.a]
  data = 8
  [z.b]
  data = 8
  [a.c]
  data = 8
```

The eye is likely to assume there are 3 `data = 8` values under `z` node children, when the last one is actually under `a`.

However, this particular case would be prevented by https://github.com/toml-lang/toml/issues/446

**Comment by ChristianSi** [comment]
Indentation is irrelevant for the TOM spec, since it's insignificant. Use whatever indentation style you like (if any).

**Comment by scooter-dangle** [comment]
> Indentation is irrelevant for the TOM spec, since it's insignificant. Use whatever indentation style you like (if any).

My point is that being able to directly enter nested tables makes any indentation style (other than no indentation at all) in TOML deceptive. I think that TOML's aim of being obvious applies to reading TOML, not just writing TOML. The spec's current combination of entering nested tables and agnosticism to indentation makes it non-obvious for the reader to understand what structure is being described.

**Comment by TheElectronWill** [comment]
> Even with indentation that fully reflects the depth of nesting, the reader still has to ignore the first impression that the two nested tables are direct siblings and notice that they actually have different parents within a
```toml
[a]
data = 9
  [a.b.a]
  data = 17
  [a.d.b]
  data = 17
```
I don't get the problem here. My first impression when I read this is that a has some subtables "b.a" and "d.b" that are obviously sub-sub tables. If it disturbs you, just write the intermediate level.

I think that, since it's a matter of taste, there is no point in changing the specification.
