### ISSUE TITLE
List of key-value

### ISSUE THREAD

**Issue by karantan** [toml-lang/toml#559]
How can you have ordered list of key-value pairs?

In JSON you can have something like:

```json
{
  "Plan-25": {
    "name": "Plan - 25",
    "id": 76,
    "downgrades": [
      {
        "id": 75,
        "name": "Plan - 15"
      },
      {
        "id": 74,
        "name": "Plan - 10"
      }
    ]
  }
}
```

Which is equivalent to yaml's:
```yaml
Plan-25:
  name: Plan - 25
  id: 76
  downgrades:
      - id: 75
        name: Plan - 15
      - id: 74
        name: Plan - 10
```

How can you do the same thing in toml? The closes thing was this:

```toml
[Plan-25]
    name = "Plan - 25"
    id = 76
    [Plan-25.downgrades]
        [Plan-25.downgrades.Plan-15]
            id = 75
            name = "Plan - 15"
            position = 1
        [Plan-25.downgrades.Plan-10]
            id = 74
            name = "Plan - 10"
            position = 2
```

But you need to add `position` and order by position in the code which is something I would like to avoid.

**Comment by eksortso** [comment]
Tables in TOML are always unordered. But you can use an array of tables to get the ordering that you want.

Here is the equivalent of your JSON. You won't need an extra `position` value.

```toml
# Valid in TOML v0.4+
[Plan-25]
name = "Plan - 25"
id = 76

# Double brackets define elements of an array of tables.
[[Plan-25.downgrades]]
id = 75
name = "Plan - 15"

[[Plan-25.downgrades]]
id = 74
name = "Plan - 10"
```
