### ISSUE TITLE
Top level key/value ordering

### ISSUE THREAD

**Issue by DavidWells** [toml-lang/toml#565]
Hello there!

Is is possible to have a single key/value pair below `[thing]` declarations?

**Example:** 

The below config is what I'd like to achieve. But `otherThing` rolls under `build.otherThing`. 

```toml
[build]
  publish = "build"
  command = "npm run dev"

otherThing = "this doesnt work"
```

This toml (below) is the correct values but I'd like to not put all the single value key/value pairs at the the top of the file but rather closer to what they related to.

```toml
otherThing = "this does work"

[build]
  publish = "build"
  command = "npm run dev"
```

Is is possible / is there syntax to have a single key/value pair below `[whatever]` declarations?

Maybe something like this?

```toml
[build]
  publish = "build"
  command = "npm run dev"

[otherThing] = "¯\_(ツ)_/¯"
```

Many thanks!

**Comment by TheElectronWill** [comment]
Top-level key/value pairs must be at the top of the file. You cannot return to the top level once you've opened a table.

In your case, you could do this:
```toml
[build]
  publish = "..."
  command = "..."

[misc]
  otherThing = "this is misc.otherThing"
```

**Comment by DavidWells** [comment]
@TheElectronWill thanks for the response.

That won't achieve the desired result however 😅

They nests `otherThing` under an unnecessary property of `misc`

I suppose the only way to do this is keeping all top level keys at the top. Bummer. 

Like:

```toml
otherThing = "this does work"

[build]
  publish = "build"
  command = "npm run dev"
```

It would be great in a future version of the spec if top level keys could be used after `[thing]` declarations.

Like:

```toml
[build]
  publish = "build"
  command = "npm run dev"

[otherThing] = "value"
[otherNotImportantThing] = "down here"
```

**Comment by eksortso** [comment]
@DavidWells I'd like to ask a question: _Why_ do you want to add more key-value pairs to the top level? You mentioned that you want these values close to the things they are related to, but wouldn't that suggest that those values properly belong in the subtables as well?

TOML was created as a configuration format, so it assumes that all the stuff at the top level is so important that it needs to be kept at the top of the file, before subtables are introduced. Will it always be that way? Who knows? Maybe TOML will evolve into something more than a config format, which we might see happening now. But since TOML is intended to be Obvious and Minimal, any syntax allowing the top level to move around needs a strongly expressed reason to exist.

I await your response to my question, but I want to thank you for raising your question in the first place. This is a topic that's come up explicitly in the past (#456), but new information can change minds.

**Comment by DavidWells** [comment]
Hey @eksortso thanks for the response!

This is actually for a use case where I'm extending `toml` to support file references.

Config files of any format can become rather large and splitting them up into smaller discrete units sometimes makes sense (IMO 😁). 

So for example, I might have a config file like this with a logical ordering of what should go where (a.k.a main settings up top, and less important settings below)

```yml
# Site Settings
settings:
  id: Your_Site_ID

# Build settings
build:
  base: project/
  publish: project/build/
  command: echo 'default context'
  functions: project/functions/

... other stuff 

# All Site Redirects
redirects: ${file(./redirects.yml}

# All Site Headers
headers: ${file(./headers.yml}
```

Here is the `toml` equivalent, where I am forced to place things that might not be as semantically important at the very top.

```toml
redirects = "${file(./redirects.toml}" # ref to very large file
headers = "${file(./headers.toml}" # ref to very very large file

[settings]
id = "Your_Site_ID"

[build]
base = "project/"
publish = "project/build/"
command = "echo 'default context'"
functions = "project/functions/"

... other stuff 
```

It's not the end of the world, but I does make it a little less straight forward to parse as whats important. Ideally the ordering could be the same in both formats. Possibly with `[foo] = "bar"` declaration (or something)

I think have a way to define top level keys anywhere inside of the `toml` file would be a nice feature and match feature parody with `yml`, & `json` (where you can define top level keys and order them how you wish)

**Comment by eksortso** [comment]
Hi @DavidWells, thanks for responding! This has been a long time coming, and I apologize for not replying earlier.

The new syntax that you're suggesting, that `[foo] = "bar"`, does suggest a future way to import files. But it may be better to avoid new syntax if we can, and instead see what conventions arise for handling imports.

In your example, it looks like you can retain the order you want without changing the syntax. You have four sections in your original file: `settings`, `build`, `redirects`, and `headers`. We can keep it that way; we'll make `redirects` and `headers` into tables, and it looks like they're intended to be tables in the end, anyway. With special keys, you can refer to the files intended to populate them. Then when you load the config file, you can later on open and load those files, keeping their contents in their proper sections.

So consider the following. I put the special key `$file` in `redirects` to specify the file reference, and did the same in `headings`. Would this work for you?

```toml
[settings] # Site Settings
id = "Your_Site_ID"

[build]
base = "project/"
publish = "project/build/"
command = "echo 'default context'"
functions = "project/functions/"

# ... other stuff

[redirects]
"$file" = "./redirects.toml" # ref to very large file

[headings]
"$file" = "./headers.toml" # ref to very very large file
```

**Comment by pradyunsg** [comment]
I agree with @eksortso's suggestion that this is something that is doable without  adding new syntax.

**Comment by sgarciac** [comment]
> maybe this could make it possible?
> 
> ```toml
> [a]
> x = "a.x"
> 
> [] # back to root
> b = "b"
> ```

It would break the rule of not "re-opening" a table

**Comment by pradyunsg** [comment]
Note that this is a duplicate of #456 and the syntax and idea has also been proposed in the past.

**Comment by LongTengDao** [comment]
> > maybe this could make it possible?
> > ```toml
> > [a]
> > x = "a.x"
> > 
> > [] # back to root
> > b = "b"
> > ```
> 
> It would break the rule of not "re-opening" a table

Indeed. Reopen a table is a really bad idea, the rule is right, and the root table is no exception.

Even if we need to reopen a root, it also can't be no limit. (@pradyunsg Thanks for notice the history reference material)

Maybe the limit of below could make it less damage:
1.  only root table
2.  only end of the file
3.  only one time

Then how about this?

```toml

a = 1
b = 2

[c]
x = 1
y = 2

[d]
x = 1
y = 2

---

e = 1
f = 2

```
