### ISSUE TITLE
A style guide for toml?

### ISSUE THREAD

**Issue by yjqiang** [toml-lang/toml#608]
We shouldn't force user to follow the rules since it would be hard for developers to verify the style and parse toml file. But I think we can make a style guide just like https://www.python.org/dev/peps/pep-0008/ .  For example, `Use 4 spaces per indentation level.` or  `Limit all lines to a maximum of 79 characters.`.

**Comment by bd82** [comment]
A style guide is interesting.

I've created a Prettier Toml Plugin which could enforce (most of?) the rules of such a style guide.
https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml

**Comment by LongTengDao** [comment]
How about this?

```toml
# comment

[chapter]

w = [ "...", "..." ]
uu = [
     "...",
     "...",
]

[chapter.section]

w = { w = "...', uu = "..." }
uu = """
..."""

```

1. Never use indent unless in inline array, for multi-line strings written.
2. Single space as the sample above showed.

**Comment by yjqiang** [comment]
> How about this?
> 
> ```toml
> # comment
> 
> [chapter]
> 
> w = [ "...", "..." ]
> 
> uu = [
>    "...",
>    "...",
> ]
> 
> [chapter.section]
> 
> w = { w = "...', uu = "..." }
> 
> uu = """
> ..."""
> ```
> 
> 1. Never use indent unless in inline array, for multi-line strings written.
> 2. Single space as the sample above showed.

Maybe no need to add one line in the same part?
```toml
[chapter]
w = [ "...", "..." ]
uu = [
   "...",
   "...",
]
```

**Comment by LongTengDao** [comment]
> Maybe no need to add one line in the same part?
> 
> ```toml
> [chapter]
> w = [ "...", "..." ]
> uu = [
>    "...",
>    "...",
> ]
> ```

Each below is not clear...

```toml
# comment
[chapter]
w = [ "...", "..." ]
uu = [
   "...",
   "...",
]
[chapter.section]
w = { w = "...', uu = "..." }
uu = """
..."""
```

```toml
# comment

[chapter]
w = [ "...", "..." ]
uu = [
   "...",
   "...",
]

[chapter.section]
w = { w = "...', uu = "..." }
uu = """
..."""
```

```toml
# comment

[chapter]

w = [ "...", "..." ]
uu = [
   "...",
   "...",
]

[chapter.section]

w = { w = "...', uu = "..." }
uu = """
..."""
```

**Comment by yjqiang** [comment]
And in readme, you can see this, using indent to declare different level
```toml
[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"
```

**Comment by LongTengDao** [comment]
> But here is the problem, what if we mix them(sub-table and key/value pair)?👇 Now I'm confused, do we need indent to declare the leve?

I understand what you said. So I prefer "no".

> otherwise, the most special design of whole table name chain in TOML is useless—wordy and aligned

**Comment by yjqiang** [comment]
> I understand what you said. So I prefer "no", never indent unless in multi-line inline array.

I like python. So if we don't care about the readme, I prefer this.

```toml
# I wrote by myself
[database]
  server = "192.168.1.1"
  ports = [ 8001, 8001, 8002 ]
  connection_max = 5000
  enabled = true
```

**Comment by LongTengDao** [comment]
> I like python. So if we don't care about the readme, I prefer this.
> 
> ```toml
> # I wrote by myself
> [database]
>   server = "192.168.1.1"
>   ports = [ 8001, 8001, 8002 ]
>   connection_max = 5000
>   enabled = true
> ```

Then why not YAML...

> > I understand what you said.
> 
> Sorry for my poor English skills. 😂

Oh, I mean I got your use case, not about the language. I'm also Chinese.

**Comment by yjqiang** [comment]
> Then why not YAML...

Good idea. lol

**Comment by LongTengDao** [comment]
> > Then why not YAML...
> 
> Good idea. lol

It's just a rhetorical question. In fact, I have wrote an article to recommend TOML, and compare it with INI/JSON/JSON5/YAML. <https://ZhuanLan.ZhiHu.com/p/50412485>

The advantage of TOML (compare with YAML) is:

1. Editing and reading indent-base config file always make people nervous, being afraid of counting levels incorrectly, especially using 2 spaces indent.
2. In trite editing UI, which not support multi-line indent/back-indent together or auto indent while breaking line, editing indent-base config file is very bothering.
3. Here is too much magic in YAML, which you need all know in the beginning, even if you only want to use the basic features. e. g., what's the rule for bare key name? Would you quote all key names?
4. How to specify a multi-line string precisely? I mean precisely control the starting and ending empty lines.

**Comment by pradyunsg** [comment]
Thanks for filing this @yjqiang!

Having a style guide might not be needed for TOML given that it's already a fairly strict language in some senses and additionally, it is designed for being human-consumable.

That said, I do see that there might be some value in having a guide and I welcome folks to do so as an "external" effort for this; to see if the community of TOML users care enough. I'll be more than happy to adopt a popular style guide as the "TOML Style Guide" if a popular style guide emerges. I welcome @bd82 or @yjqiang to champion such an effort, if they wish to.

@LongTengDao That's a nice blog post. Thanks for writing it.

---

I'll close this issue since I don't think there's anything actionable for me here but please feel free to mention me, if you feel like there's more discussion to be had here. :)

**Comment by sisrfeng** [comment]
> never use indent in toml unless ...
Indent is elegant and clear.
Personally,  I use indent to make the structure of the file very clear. And I use vim and `set fdm=indent`, for most syntax, like python, (vim's) help, tex, man.


> why not yaml
Because we ,as a user, can not use yaml if the tool is configured through toml file.

**Comment by eksortso** [comment]
@sisrfeng I'm sorry, but your example is not just confusing, but also invalid.

I understand why you would prefer to use indents, even though they aren't necessary. But It's important to maintain clarity by not implying that indentation is significant. For instance:

```toml
[pager]
    # ...

    [[columns]]  # NOTE: Not pager.columns!
        # ...
```

The table `pager` and the array `columns` are both located at the same level, in the root table. The indentation used here is deceptive, because the `columns` array is not part of the `pager` table! Avoid indentation that may lead to this confusion.

I can also understand why you want to align your equals signs. The extra whitespace keeps the keys and the values separated visually. The downside to this, though, is that if your keys' names are significantly shorter than the longest name, you visually lose the connection between the name and the value. Since keys within a table need not be listed in any particular order, what would happen if you changed the order of your keys, when you relied heavily upon their order when writing your config files? Save yourself some trouble, and keep keys close to their values.

In TOML, all strings must be written in quotes. Unlike YAML, bare words can never be strings. This prevents ambiguity, which to this day still plagues YAML. Your `pager` table, without the extra lines, ought to look like the following:

```toml
[pager]
mode = "Disable"
detect_width = false  # this is a boolean
command = "bat"
```

You may use indentation and alignment however you wish, but keep this advice in mind. And always write strings in quotes.
