### ISSUE TITLE
Ambiguous ABNF issues with multiline basic strings

### ISSUE THREAD

**Issue by mmakaay** [toml-lang/toml#640]
Are the following cases valid?

``` toml
x="""""""""

y="""X""""""
Y"""
```

Personally, I don't think so and according to the spec I would say that the triplet quotation marks inside the  multiline string ought to be escaped to prevent confusion with the closing triplet quotation marks. The ABNF definition however allows this syntax. It also is ambiguous; instaparse returns two possible parsing routes for this input.

When I change the input to
``` toml
x="""\"\"\""""

y="""X\"\"\"\"\"\"
Y"""
```
then the ABNF is still ambiguous. One of the parsing results is a keyvalue pair with key = "x" and the value is the rest of the document, so eating key = "y" as part of the value of "x" as well.

The minimal case for triggering the ambiguous behavior is this one:

``` toml
x=""""""
y=""""""
```
