### ISSUE TITLE
Support + in key names

### ISSUE THREAD

**Issue by BrianHarris** [toml-lang/toml#644]
I'm working on a system that allows for merging TOML files together. For example you could have a "Base" config and a platform specific "Override" config.

For scalars it's easy -- overwrite the old value. For arrays it's tricky though because we want the ability to add and remove elements.

I'd like the ability to prefix a key or table name with + to indicate it should be added to an existing array, or - to indicate it should be removed. For example:

[table]
+key=[ "These elements", " are added to an existing key" ]
-key=[ "These elements", " are removed from an existing key" ]

I can do it right now by enclosing the name in quotes, but it would be really nice to specify them with bare keys.

Alternatively, TOML could support explicit merging with += and -= operators, but that seems like a much bigger change.

**Comment by eksortso** [comment]
Dashes can already be used in bare keys, including at the beginnings of key names. So we're just talking about the plus signs here. That said, I'm up-and-down about this proposal.

The simplest approach to fulfilling this enhancement request would be to add plus signs ("`+`") to the list of acceptable `unquoted-key` characters. So this would permit keys like `apples+oranges` to go without quotes, as well as keys beginning with plus signs, such as `+one`. Doing so would be simple, as plus signs don't have any other significant meaning in TOML at this time 

This is being requested so that a file for an application intended to alter an existing configuration can also be written easily as TOML. But color me skeptical about making such documents easier to write. Since an application to make modifications to existing configs is certainly an extraordinary application, I am not sure if we ought to make it easier, just for that purpose.

**Comment by BrianHarris** [comment]
Right Dave, The easiest way to accomplish what I need is to add "+" as an allowed character. I'm not sure what the disadvantages of doing that are. I read through #283 and all the issues it links to. I understand originally keys could contain anything, then it was proposed to restrict them to alpha-numeric only, but dashes were added because the Rust people needed them for Cargo. Adding + seems easy enough, but it could be a 'slippery slope' to allowing any character again.

**Comment by ChristianSi** [comment]
Adding "+" as an allowed character feels pretty safe and reasonable to me. Besides this (obscure) use case it might also come handy in other situations, allowing designers to name their keys "apples+oranges", "Musicians+Artists" etc.

I don't think that we risk a "'slippery slope" as long as the allowed keys remain limited to those printed on the keycaps of a standard US QWERTY keyboard.

**Comment by mmakaay** [comment]
Can I propose an alternative? Wouldn't it work to make use of the following configuration style, which IMO also makes it more clear to the reader what you're doing with the data? ("a + or - at the start of the key has special meaning" only works for those who are familiar with the configuration system already:

```toml
[table]
key.add = [ "These elements", " are added to an existing key" ]
key.remove = [ "These elements", " are removed from an existing key" ]
``` 

this style also allows for many other typical schemes that you might come up with during configuration management-like tasks, for example:

```toml
[table]
key.replace = { search="$HOSTNAME", replace="production.example.com" }
key.insert = [ "tier1.example.com" ] # insert items at the start of the array
key.append = [ "tierx1.example.com", "tierx2.example.com" ] # append items to the end
key.dictFromQuery = "SELECT key, value FROM configuration WHERE env='production'"
key.unset = true
# ... etc ...
```

Wouldn't these be more clear than the special meaning of "+" and "-" ?
Also, with that encoding, I could foresee issues with the way in which to use them:
```
[table]
+sub.key = [ 1, 2, 3 ]  # would this be right?
sub.+key = [ 4, 5, 6 ]  # or this one? Or maybe both?

sub.key.append = [ 1, 2, 3 ] # while this is crystal clear.
```
