### ISSUE TITLE
Maybe we should clarify array-of-tables usage?

### ISSUE THREAD

**Issue by workingjubilee** [toml-lang/toml#651]
I recently saw this fascinating TOML format (details changed to protect the accused):

```toml
[[fruits]]
name="pomegranate"

[fruits.tastes] # wait, what?
forbidden=true
sweet=true
spicy=false

[[fruits]] # et cetera
```

Is that `[fruits.tastes]` table opening consistent with intended array-table usage?

**Comment by ChristianSi** [comment]
@workingjubilee Sure, that's valid, it defines "fruits.tastes" as a subtable under the first "fruits" table (the one defined above). Using dotted keys, the same structure could be described, arguably more readable, as follows:

```toml
[[fruits]]
name="pomegranate"
tastes.forbidden=true
tastes.sweet=true
tastes.spicy=false

[[fruits]] # et cetera
```

More interesting is the case where the subtable is defined *before* the first entry of the table array:

```toml
[fruits.tastes]  # uh, where does this go?
forbidden=true
sweet=true
spicy=false

[[fruits]]
name="pomegranate"

[[fruits]] # et cetera
name="apple"
```

The spec is silent on how to handle this perversion. Some parsers might treat it to in the same way as the first example, but arguable, it should be forbidden.

Another issue about which the spec might be clarified are attempts to mix table arrays and plain tables. The spec already says: "Attempting to define a normal table with the same name as an already established array must produce an error at parse time", giving this example:

```toml
[[fruit.variety]]
  name = "red delicious"

# This table conflicts with the previous table
[fruit.variety]
  name = "granny smith"
```

While some might consider it as obvious, it would be useful to add a "or vice versa" to make it clear that the reverse order is forbidden too:

```toml
[fruit.variety]
  name = "granny smith"

# This table conflicts with the previous table
[[fruit.variety]]
  name = "red delicious"
```
