### ISSUE TITLE
Explain ordering of subtables under arrays of tables

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#658]
The spec says: "You can create nested arrays of tables as well. Just use the same double bracket syntax on sub-tables. Each double-bracketed sub-table will belong to the most recently defined table element above it."

This does not, however, explicitly mention that case that the subtable is a regular table rather than a table array -- though clearly the spec expects this case to be valid as well. This too should be mentioned and a suitable example added, e.g.

```toml
[[fruits]]
name = "pomegranate"

[fruits.tastes]
forbidden = true
sweet = true
spicy = false

[[fruits]]  # et cetera
name = "peach"
```

The spec also should make it clear that defining subtables (whether regular tables or arrays) *before* the first entry of a table array is not allowed, since it's not clear to which element of the (so far empty) table array they should be attached.

```
# INVALID
[fruits.tastes]  # this works only if "fruits" is a regular table
forbidden = true
sweet = true
spicy = false

[[fruits]]  # parser should throw an ERROR upon discovering that it's a table array
name = "pomegranate"

[[fruits]]  # et cetera
name = "peach"
```

Another issue about which the spec might be clarified are attempts to mix table arrays and plain tables. The spec already says: "Attempting to define a normal table with the same name as an already established array must produce an error at parse time", giving this example:

```toml
[[fruit.variety]]
  name = "red delicious"

# This table conflicts with the previous table
[fruit.variety]
  name = "granny smith"
```

While some might consider it obvious, it would be useful to add a "or vice versa" to make it clear that the reverse order is forbidden too:

```toml
[fruit.variety]
  name = "granny smith"

# This table conflicts with the previous table
[[fruit.variety]]
  name = "red delicious"
```

This issue is a spin-off of #651 – thanks @workingjubilee for bringing this to my attention.

@pradyunsg: Maybe add it to the critical path for TOML 1.0?
