### ISSUE TITLE
Way to implement "\ " for stored shell commands?

### ISSUE THREAD

**Issue by keiichiiownsu12** [toml-lang/toml#662]
I have a shell command stored in a value that normally requires me to escape out spaces using '\ ', i.e. a backslash followed by a space. This is for a .toml configuration file from the gebaard project (it's a touchpad multi-touch gesture parser*): [https://github.com/Coffee2CodeNL/gebaar-libinput](url)

Snippit from the .toml file:

```toml
[commands.swipe.three]
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch\ One\ Desktop\ to\ the\ right"
```

This is meant to execute the qdbus method -- a kde/kwin method for switching virtual desktops -- on a left swipe. Normally for the command to be executed in a shell, the entire command either needs to be quoted or the spaces escaped with "\ ". Unfortunately, it appears '\ ' is an illegal escape character, as when I try running the requisite program that parses the above .toml file, I am returned with this error: 
`terminate called after throwing an instance of 'cpptoml::parse_exception'
  what():  Invalid escape sequence at line 8
[1]    12435 abort (core dumped)  gebaard
`

So my question would be, since the value to be parsed from the .toml file is supposed to be a shell command that requires spaces to be escaped, is there a way for me to properly write this in a/the .toml file?
