### ISSUE TITLE
Whitespace in keys

### ISSUE THREAD

**Issue by sheerun** [toml-lang/toml#667]
The documentation says whitespace in keys is ignored:

> Whitespace around the key is ignored, however, best practice is to not use any extraneous whitespace.

So how to create key that contains whitespace? JSON and Yaml easily allow it.

```json
{
  "Hello world": { "foo": "bar" }
}
```

```yaml
'Hello world':
  foo: bar
```

```toml
[Hello world] # ??? doesn't work
foo = "bar"
```

**Comment by mmakaay** [comment]
The keyword here is "around" instead of "in".
If you need whitespace "in" a key name, then you can make use of the following valid form:
```toml
["Hello world"] # does work
foo = "bar"
```
What "whitespace around the key is ignored" aims at, is that
```toml
[    Hello   ]
foo = "bar"
```
is valid, where "Hello" is the table key name, instead of maybe "   Hello   ".
