### ISSUE TITLE
Cross table variable sharing

### ISSUE THREAD

**Issue by codeBehindMe** [toml-lang/toml#686]
Is it possible to inject variables across tables?

*Example:*
```
[dev]
connstring = "abcd"
[test]
connstring = dev.connstring
```

*Similar implementation in other languages:*
```
# yaml
dev: &dev
  connstring = "abcd"
test:
  <<: *dev

# This is available as ['test']['connstring']
```

*Use case(s):*
Mapping configuration to environments, often many configuration variables are duplicated. It'll be nice to declare once and map across tables. 

Open to alternatives.

**Comment by ChristianSi** [comment]
The TOML spec offers no such functionality, but you could do it in your own application, say:

```toml
[dev]
connstring = "abcd"

[test]
connstring = "{{dev.connstring}}"
```

And implement your app to make it replace each ``{{...}}``string with the specified value.

Another option would be to specify a `[default]` section whose values will be used unless overwritten by key-value pairs in another section.

```toml
[default]
connstring = "abcd"

[dev]
# no connstring defined, hence the one from [default] will be used

[test]
connstring = "efg"  # replaces the [default] value
```

Again, implementing the fallback lookup would be up to your implementation; a TOML parser by itself will not treat the `[default]` section in any way special.
