### ISSUE TITLE
Clarification: Multiple inline arrays of tables with the same key

### ISSUE THREAD

**Issue by vrom911** [toml-lang/toml#740]
Is this the valid TOML:

```toml
foo = [ {a = 1}, {b = "bar"} ]
foo = [ {c = true} ]
```

And if yes, is this equivalent to the following:

```toml
[[foo]]
  a = 1
[[foo]]
  b = "bar"
[[foo]]
  c = true
```
