### ISSUE TITLE
Mixing tables and dotted keys of elements within that table

### ISSUE THREAD

**Issue by leoncvlt** [toml-lang/toml#741]
Hi all, earlier I've naively tried to parse some toml code similar to this:
```toml
[fruits]
  [fruits.apple]
    color = "red"

    [[fruits.apple.properties]]
    name = "flavour"
    content = "delicious"

    [[fruits.apple.properties]]
    name = "nutrition"
    content = "abundant"

    [fruits.apple.translations]
    it = 'Mela'
    fr = 'Pomme' 

# dotted key
fruits.orange.color = 'orange'
```

which parses into this:
```json
{
   "fruits":{
      "apple":{
         "color":"red",
         "properties":[
            {
               "name":"flavour",
               "content":"delicious"
            },
            {
               "name":"nutrition",
               "content":"abundant"
            }
         ],
         "translations":{
            "it":"Mela",
            "fr":"Pomme",
            "fruits":{
               "orange":{
                  "color":"orange"
               }
            }
         }
      }
   }
}
```

As you can see, the `orange` item spills inside apple's `translations` table, while I want it to be its own definition inside the `fruits` table. While it sounded right on paper, while re-reading the specification I noticed it says you cannot define a table more than once, which I assume it's what's happening here.

The code parses fine if I move `orange` to its own `[fruits.orange]` table and have `color` as a key of it, but is there a way to mix tables definitions and using inline dotted keys to define properties for that same table? My use case is that while `apple` would have a lot of properties, `orange` and some other fruit would only have the `color` key defined and therefore would be less verbose to quickly define it as a dotted key instead of building a table for each fruit.
