### ISSUE TITLE
The spec language seems to forbid writing to the same defined table using dotted keys

### ISSUE THREAD

**Issue by Validark** [toml-lang/toml#769]
(I may have made some mistakes in this write-up, but I hope I have made the contradiction obvious by the time you get to the end. Please read to the end, because I may be identifying multiple problems, so if you feel I am wrong about one issue you should still consider the rest of this write-up.)

Let's start here:

> Dotted keys define everything to the left of each dot as a table. Since tables cannot be defined more than once, redefining such tables using a `[table]` header is not allowed. Likewise, using dotted keys to redefine tables already defined in `[table]` form is not allowed.

The contradiction is here:
  1. Dotted keys define everything to the left of each dot as a table.
  2. tables cannot be defined more than once

Here, "define" must mean explicitly defined (because tables can be implicitly defined multiple times by either dotted keys or headers) and no delineation is made between tables "defined in dotted keys" versus tables defined in headers (referred to elsewhere in the spec as "directly defined"). It is stated that any table (explicitly) "defined" cannot be (explicitly) "defined" again. That means this should be invalid:

```toml
[fruit]
apple.color = "red" # Here, apple is "defined as a table"
apple.taste.sweet = true # Here apple is "defined" AGAIN as a table
```

I would also add that the spec should explicitly state that "dotted keys" can NOT refer to keys separated by dots inside headers. Otherwise, that would also mean that defining headers out of order would be invalid.

```toml
[fruit.apple]
# `fruit` is implicitly defined as a table
# `apple` is explicitly defined as a table within `fruit`

[fruit]
# fruit is explicitly defined as a table

# of course, this document should be valid!
```

Now, if you interpret "define" as implicitly defined in this case, that still doesn't work. More on this later.

We see the following elsewhere in the spec:

> As long as a key hasn't been directly defined, you may still write to it and to names within it.
  ```toml
  # This makes the key "fruit" into a table.
  fruit.apple.smooth = true
  
  # So then you can add to the table "fruit" like so:
  fruit.orange = 2
  ```

The above is the only place in the spec where the term "directly defined" is used to delineate between the different kinds of "define". (Aside from where it says that in-line tables are "fully defined" at their location and cannot be added to or modified, but that is pretty air-tight so I don't want to focus on it at all.) 

The (first) paragraph in question is followed by "The [table] form can, however, be used to define sub-tables within tables defined via dotted keys." I don't appreciate how the first two examples follow naturally from the principle "Since tables cannot be defined more than once" but the third example is a contradiction of the principle. It's fine for all three of these examples to be fine in TOML, but not without delineating between the different kinds of "define". 

The contradiction leads me to question whether the following is an example of a valid contradiction of the aforementioned principle:

Is it valid for "dotted keys" (not in headers) to modify something implicitly defined as a table in a header? My guess is yes, since if you change the order it is valid.

```toml
[fruit.apple.taste]
# `fruit` is implicitly defined as a table
# `apple` is implicitly defined as a table in `fruit`
# `taste` is explicitly defined as a table in `apple`
[fruit]
# fruit is explicitly defined as a table
apple.color = "red"
# apple is (indirectly) defined as a table with color set to "red"
```

While there are occurrences in the spec where you can easily infer the difference between the kinds of "define" being used (including in some examples above), the top quotation seems to imply it is possible to possible to implement the "dotted keys" by only delineating between defined tables and implicitly defined tables (leaving aside arrays and in-line tables for now), when in fact, it is not possible. You HAVE TO delineate  between dotted key definitions (not in headers) versus header definitions. There is no way to satisfy all the rules any other way.

-------------

Here is an example of an implementation. It's a bit TypeScripty, hopefully others can understand what I am getting at.

Define enum `ScopeType` as having members: `{ Inferred, Defined }`
Define `scopeTypes` as a Map/Hash of `Table -> ScopeType`.
Let `global` be the global scope

###### A `Map` pairs keys with values, and has methods "has", "get" and "set". "has" returns whether a mapping exists for a given key. "get" returns what a given key maps to. "set" maps a given key to a given value. In this case, ScopeTypes.has(value) is another way of expressing that a given value is not a literally defined value, e.g.`1` or `false`

```toml
[a]
# assert global["a"] == undefined or scopeTypes.get(global["a"]) == ScopeType::Inferred
# define `a` as global["a"] or an empty table {}
# scopeTypes.set(a, ScopeType::Defined)

b.c = 1
# assert a["b"] == undefined or scopeTypes.has(a["b"])
# scopeTypes.set(b, ScopeType::Inferred)

[a.b] # should be forbidden
# assert global["a"] == undefined or scopeTypes.has(global["a"])
# define `a` as global["a"] or an empty table {}
# scopeTypes.set(a, ScopeType::Inferred)

# assert a["b"] == undefined or scopeTypes.get(a["b"]) == ScopeType::Inferred
# define `b` as a["b"] or an empty table {}
# scopeTypes.set(b, ScopeType::Defined)
```

The crux of the problem here is in our `[a.b]` logic, where `b` may only be `Inferred`, in order to allow these cases:

```toml
[a.b.c]
[a.b]
# `a` is Inferred
# `b` was Inferred, but is now Defined
```

```toml
[a]
[a.b] # `a` is Defined
# `b` was undefined, is now Defined
```

And block this case:
```toml
[a.b]
# b is defined
[a.b]
# b is defined already! error!
```

Hence, there is no way to block "redefining such tables [tables defined by dotted keys] using a [table] header is not allowed." E.g.

```toml
[a]
b.c = 1
[a.b] # forbidden?
# `a` is Inferred
# b is must be Defined in order to block this
```

So let's rewrite our logic where we set `b` in `b.c = 1` to be Defined in order to account for the above case:

```toml
a.b = 1
# assert global["a"] == undefined or scopeTypes.get(global["a"]) == Defined
# define `a` as global["a"] or empty table {}
# scopeTypes.set(a, ScopeType::Defined)
# set a["b"] = 1
```

Now we can't block this:
```toml
[fruit.apple]
# fruit is Inferred
# apple is Defined

[fruit]
# fruit is Defined

apple.color = "red" # This is acceptable by the above logic

# To block this, we'd need to assert `apple` is not Defined
```
There is no way to block the above document without blocking the use of the same dotted-key-defined-table using only 2 `ScopeType` enums.
```toml
a.b = 1
# `a` is Defined here

a.c = 2
# We must allow `a` to be Defined for this
# But if we allow `a` to be Defined, we can't block the previous case!
```

I am trying to get the point across using code here because I don't know of a better way to express this technically. **We need to delineate between dotted key define's versus header define's in the spec in order for it to make logical sense.**

(I may have made some mistakes in this write-up, but I hope I have made the contradiction obvious by the time you've managed to read this far.)

**Comment by genericptr** [comment]
Yes, I think you had the same problem. The concept of "define" was not clear enough for me and it could use it's own paragraph in the spec. I closed my issue #770 because I didn't think this was the place for tech support but maybe the author of the spec wants to actually make some changes.

**Comment by ChristianSi** [comment]
I believe that has been sufficiently explained in the comments to #770 and #771 and can therefore be closed. Or is anything still unclear?

**Comment by pradyunsg** [comment]
If anyone has a specific wording change to suggest, I'm all ears. Otherwise, I'd say I'll close this when I come back around to this. :)

**Comment by Validark** [comment]
I appreciate the conception of the spec given in #771. I think it answers all the problems I identified. In the next few days I'll write something to clarify this in the spec. Having just learned this, I understand which parts aren't as clear as they could be.

**Comment by ChristianSi** [comment]
I think this was sufficiently addressed by #795 and can therefore be closed.

**Comment by pradyunsg** [comment]
Indeed!

**Comment by Validark** [comment]
Sorry for being inactive, but it seems to me like this problem is still present in the latest version of the spec:

> Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created.
> ```toml
> fruit.apple.color = "red"
> # Defines a table named fruit
> # Defines a table named fruit.apple
> 
> fruit.apple.taste.sweet = true
> # Defines a table named fruit.apple.taste
> # fruit and fruit.apple were already created
> ```
> Since tables cannot be defined more than once, redefining such tables using a [table] header is not allowed. Likewise, using dotted keys to redefine tables already defined in [table] form is not allowed. The [table] form can, however, be used to define sub-tables within tables defined via dotted keys.

IMO this is still contradictory (fruit and fruit.apple were already created **AND defined**, at least going solely by the language in the spec) and doesn't adequately convey https://github.com/toml-lang/toml/issues/771#issuecomment-696796941 

This language "Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created" has a few problems. What do dotted keys do if such tables were previously created? Are they.... invalid? This still doesn't answer whether a previously created (by `[headers]`) table can be defined by dotted keys (they can). 

```toml
[fruit.apple.texture] # creates fruit, fruit.apple
smooth = true

[fruit]
apple.calories = 94.64 # defines fruit.apple
```

> I believe this has been sufficiently explained in the comments to #770 and #771 and can therefore be closed. Or is anything still unclear?

I understand how TOML works now, due to our discussion threads, but this is important behavior to explain in the spec because [@marzer/tomlplusplus](https://github.com/marzer/tomlplusplus) still gets this wrong... https://godbolt.org/z/K53Tb7

I also don't think its good to keep the term "directly defined" in the spec after introducing the concepts of a table being "created" vs being "defined". Again, what makes something directly defined versus not directly defined? Are things indirectly defined? I think most of my original criticisms are still applicable to the latest document.

**Comment by eksortso** [comment]
>This language "Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created" has a few problems. What do dotted keys do if such tables were previously created?

_Nothing._ Such tables are already created. Read the example's comment for the extra bit of clarity that I thought was obvious. If that's still inadequate, refer back to my explainer in #795, either version of it, and the conversation that followed.

>Are they.... invalid?

_No._

>This still doesn't answer whether a previously created (by [headers]) table can be defined by dotted keys (they can).

The text that you quoted explicitly says, "using dotted keys to redefine tables already defined in `[table]` form is not allowed." So _they cannot._ Find me contradictory language that this doesn't cover.

You could excise the word _directly_ from "directly defined" and what you'd have left would mean the exact same thing, because all the means for defining key/value pairs is included in the spec. If this is still a rough edge too far, then go ahead and open a new issue, or open a PR for a future update. If there's discussion to be had, it's welcome, elsewhere. But this issue is closed.

**Comment by ChristianSi** [comment]
@Validark: I think that the spec is now reasonably clear though, of course, implementers still can and will make errors. But the behavior you found in tomlplusplus is in clear violation of the spec, which says: "The `[table]` form can, however, be used to define sub-tables within tables defined via dotted keys" (followed up by an example).

So you can file a bug there and get it fixed, if you didn't already. But that's really a problem of that specific implementation, not of the spec.

**Comment by Validark** [comment]
> > This language "Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created" has a few problems. What do dotted keys do if such tables were previously created?

> Nothing. Such tables are already created. Read the example's comment for the extra bit of clarity that I thought was obvious. If that's still inadequate, refer back to my explainer in #795, either version of it, and the conversation that followed.

This is not the correct answer. The answer is that the dotted keys define but do not create such tables.

> > This still doesn't answer whether a previously created (by [headers]) table can be defined by dotted keys (they can).

> The text that you quoted explicitly says, "using dotted keys to redefine tables already defined in [table] form is not allowed." So they cannot. Find me contradictory language that this doesn't cover.

Your quote speaks only of defined tables, and says nothing of created tables.

Again, this is what we're talking about:
```toml
[fruit.apple.texture] # creates fruit, fruit.apple
smooth = true

[fruit]
apple.calories = 94.64 # defines fruit.apple
```

**Comment by Validark** [comment]
> implementers still can and will make mistakes
@marzer has been involved in these discussions though. I don't think he misunderstood the spec as much as the spec lacks some critical points. 

https://github.com/marzer/tomlplusplus/issues/61

I think @eksortso is right though that this should be addressed elsewhere.

**Comment by marzer** [comment]
Ok, I'm way late to this party, apparently. My read of the spec when I wrote that part of toml++ was that the example above should be illegal because dotted keys were just syntactic sugar for inline tables, and thus had the same rules about not being mutable via regular `[tables]`. If I got this wrong I'll happily change it, but I don't think that _should_ be wrong. Dotted KVPs and `[tables]` being allowed to mix in that manner seems rather stupid.

**Comment by eksortso** [comment]
@Validark I owe you a response. A few bits of confusion need to be addressed, but your example at the end is a real thinker, worthy of some extra consideration. Talk to you again later.

**Comment by ChristianSi** [comment]
@marzer:

>> The [table] form can, however, be used to define sub-tables within tables defined via dotted keys
>
> Huh. Was that added recently?

Yeah, it was added by #797. You might want to check that PR to ensure that you didn't miss anything in your implementation. The PR didn't really change the meaning of the TOML spec, but it made things explicit that were formerly more or less implied.

**Comment by marzer** [comment]
@ChristianSi Roger that, thanks

**Comment by eksortso** [comment]
> @marzer:
> 
> >> The [table] form can, however, be used to define sub-tables within tables defined via dotted keys
> >
> > Huh. Was that added recently?
> 
> Yeah, it was added by #797.

No, that text was _preserved_ in #797. It was there before. The original text dates back to August 2019 in README.md.

**Comment by ChristianSi** [comment]
Oh, sorry for the confusion! But me general advice to read #797 still stands.

**Comment by marzer** [comment]
Hah. Interesting. Guess I just blew right past that snippet the first time round O_o

**Comment by marzer** [comment]
After revisiting the implementation and tests for this part of toml++ it appears I _did_ actually write a test case for the language feature in question, and my parser handles the spec's example correctly.

That is:
```toml
# "The [table] form can, however, be used to define sub-tables within tables defined via dotted keys."
[fruit]
apple.color = "red"
apple.taste.sweet = true

[fruit.apple.texture]  # you can add sub-tables
smooth = true
```

Parses correctly and yields the values and structure you'd expect. What is rejected with an error is a reversal of the two [table] headers: 

```toml
[fruit.apple.texture]
smooth = true

[fruit]
apple.color = "red"
apple.taste.sweet = true
```

If I'm understanding the language-lawyering going on here, this should in fact be **accepted**, right @eksortso?
