### ISSUE TITLE
Redefining tables is not clear

### ISSUE THREAD

**Issue by genericptr** [toml-lang/toml#770]
I'm trying to make a TOML parser but the spec rules are not clear to me. It seems that declaring existing key names allows indexing into chains of tables but the spec states this is "redefining the table" and thus contradicts itself. Please clarify what the rules are.

Does the author himself have an official parser? That would be a tremendous help in verifying our parsers follow the spec.

Examples taken from the spec:

```toml

# Since tables cannot be defined more than once, redefining such tables using a [table] header is not allowed.

[fruit]

[fruit.apple]  # INVALID
[fruit.apple.taste]  # INVALID

# QUESTION 1: Why is this allowed? fruit is already defined
[fruit.apple.texture] 
smooth = true

[[fruit]]
  name = "apple"

  # QUESTION 2: why is this allowed? fruit is already defined
  [fruit.physical] 
    color = "red"
    shape = "round"

```

**Comment by marzer** [comment]
The full example you've drawn from:
```toml
[fruit]
apple.color = "red"
apple.taste.sweet = true

# [fruit.apple]  # INVALID
# [fruit.apple.taste]  # INVALID
```

note the additional keys under the first `[fruit]` header. _Those_ are why the redefinitions are illegal; the example is demonstrating that TOML names must be unambiguous, so in the spec's example the code is trying to redefine a key-value pair as a table. The modified example TOML in your snippet is legal, because you've removed the lines where that redefinition is occurring.

**Comment by marzer** [comment]
To answer the actual questions:

```toml
# QUESTION 1: Why is this allowed? fruit is already defined
[fruit.apple.texture] 
smooth = true
```

It's allowed because this is totally legal; you're not redefining the `fruit` table, you're defining one of its children. See my clarification comment above.

```toml
  # QUESTION 2: why is this allowed? fruit is already defined
  [fruit.physical] 
    color = "red"
    shape = "round"
```

Same answer.
