### ISSUE TITLE
Does TOML need to make nesting easier?

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml#781]
This is basically an issue pulled out of #516 and #744. The underlying motivation/question is the same across both issues: how about we make writing nested tables structures easier?

I'd like to breakup the entire "space of discussion" down into these questions:

- Does TOML need to make nesting easier?
- What should that look like?
  - JSON-like? #516 is exploring how that'd look.
  - INI-like? #744 is exploring how that'd look.

---

I'm undecided/unsure about the first question, and if the answer to that is a "No", the other two issues are basically wrapped up. So... let's explore that question here. :)

**Comment by pradyunsg** [comment]
I'll quickly jot down my thoughts, before I head into what is likely going to be a long and frustrating debugging session:

- Repetition: necessary today, because the only way to reach `name` inside a `table` is to do `table.name`
  - benefit: it's immediately clear what the value refers to, since the entire path is visible not-too-far-away and without needing to look up lots of context.
  - cost: it makes authoring a TOML document bit more difficult since it's more typing and more places to update on changes.

- New syntax:
  - benefit: allows getting rid of the repetition.
  - cost: more complexity and/or stuff to know for reading/authoring TOML documents.
  - cost: we might end up introducing "too many reasonable ways to write the same thing".

**Comment by ChristianSi** [comment]
Making things easier is always good, so my general response to the question would be YES. But I think that inline tables fit into TOML's style only when used for short things, since I would leave them as they are, instead of pursuing #516. #744 on the other hand is very promising to decrease the visual clutter and repetition in table headers.

**Comment by LongTengDao** [comment]
allow newline in `{}` is really good, and maybe comma could be omitted (or optional, depends on aesthetic where we use it), to make it looks like block table:

```
[block]
a = 1
b = 1

inline = {
    a = 1
    b = {
        x = 1
        b = 1
    }
}

but-inline-with-comma = {
    a = 1,
    b = {
        a = 1,
        b = 1,
    },
}
```

---

As for short kind of section name... I can just say that it looks amazing, I need to be very patient to count which level the value belongs to.

**Comment by eksortso** [comment]
Perhaps I could bring #525 back from the dead, at least for discussion.

@LongTengDao I do prefer omitting commas when the tables extend over multiple lines. It's more TOML-like. To avoid becoming pseudo-JSON, I wanted that to be the standard, and not permit commas for mult-line inline tables.

**Comment by marzer** [comment]
> Does TOML need to make nesting easier?

Yes

> What should that look like?

An INI-like proposal, like #744. I really appreciate TOML's focus on [table headers] as a nice human-oriented document structuring device; any proposal that leans more towards JSON-like structured data representations would just dilute that strength and turn TOML into JSON 2: Electric Boogaloo

**Comment by eksortso** [comment]
Let's look at what we already have. We've got a lot.

@marzer is right about the strength of INI-style absolute-referencing headers. That is foundational to this standard, and it is imbued with a lot of flexibility for nesting subtables. #744 just strengthens that foundation. But such a standard sacrifices expressiveness in two ways, which are brought up in issues often:

1. The top level is fixed to the top of the document, before all headers, and cannot be moved. Key/value pairs are attached to the table's root. Users complain that this restriction is artificially imposed. To that, we've reiterated that the top level is so extraordinary that it makes no sense to open it up anywhere else, and that a well-designed configuration will then take advantage of subtables instead of just dumping everything in that top level. (This needs to be mentioned, even though depth is zero at this level.)

1. Subtables cannot be expressed in the middle of their parents. That's where the other options for defining tables come into play. Dotted keys offer a semi-flexible means of inserting tables in context. And inline table values provide a rigid approach to inject short tables where they're needed. These approaches are more JSON-like than INI-like. But if designed properly, configuration files on the whole do benefit from their usage.

Design comes up a lot here. I think it's important to sell the strengths of table headers to users, and to show how arbitrary subtable depths can be achieved. But at the same time, the format deliberately makes shallower subtable nesting more appealing. That benefit is worth selling.

But what about deep nesting? What can it accomplish? Perhaps quite a bit. I could imagine an elaborate machine learning model being written out in TOML, for instance. But at such levels, we go beyond normal human comprehension. Such documents are written by computers for computers to digest, with readability given a brief acknowledgement.

But that was still a selling point. A table's depth is expressed entirely by the names in its header. Braces aren't required. You could look at a TOML-based data document and navigate your way through with simple keyword searches. Those best practices have practical value.

That's my mental model, and my inner sales pitch.

**Comment by alvinometric** [comment]
For nested structures, my preference is INI-like. 
Like in the proposal from @brunoborges in https://github.com/toml-lang/toml/issues/744

```toml
[servers]
 
[#.alpha] # servers.alpha
ip = "10.0.0.1"
dc = "eqdc10"
   
[#.beta] # servers.beta
ip = "10.0.0.2"
dc = "eqdc10"
```

**Comment by brunoborges** [comment]
If I were to introduce a way to add nested blocks, I'd probably use an XML-like design here, such as:

```toml
[servers]
 
[alpha] # servers.alpha
ip = "10.0.0.1"
dc = "eqdc10"
   
[beta] # servers.beta
ip = "10.0.0.2"
dc = "eqdc10"

[/servers]
```

**Comment by eksortso** [comment]
@brunoborges Did you just introduce `servers.alpha.beta` in your example? It seems like you did.

There's no mixing absolute header names with relative ones like this.

**Comment by brunoborges** [comment]
Exactly my point, if you read the last line from my comment above :-D

If we are to introduce nesting blocks, I'd be in favor of a complete XML-like style, with all table headers having to have a table closing, like this:

```toml
​[​servers​]
 
[​alpha​] ​#​ servers.alpha​
​ip​ = ​"​10.0.0.1​"​
​dc​ = ​"​eqdc10​"​
[​/alpha​]

   
[​beta​] ​#​ servers.beta​
​ip​ = ​"​10.0.0.2​"​
​dc​ = ​"​eqdc10​"​
[​/beta]

[​/servers​]
```

**Comment by eksortso** [comment]
But then you'd just be making a more complicated XML. Folks already complain about redundant table names, so I doubt this would win anyone over.

**Comment by komkom** [comment]
I am not sure if this is the right place but here it is anyways. I don't see the benefit of allowing nested keys in 
inline tables. The only positive side I see to this is that keys in general only need one definition.
But without a deeper knowledge of toml a doc like the one below is difficult to understand IMO.

```
key = {a.b.c=1}
```

**Comment by rezamahdi** [comment]
I think https://github.com/toml-lang/toml/issues/781#issuecomment-716720352 will be so useful and may be valid in TOML, but the main issue about nesting is verbosity.

I suppose to use '...' for referring to supper table. For example this...
```toml
[server]
port=8080
[server.database]
name='dbhost'
```
.... Become this...
```toml
[server]
port=8080
[...database]
name='dbhost'
```
This will relax verbosity a little.

**Comment by eksortso** [comment]
There's a similar proposal on #744, which uses asterisks as placeholders.

Your example would look like this under the proposal:
```toml
[server]
port=8080
[*.database]
name='dbhost'
```

**Comment by nugend** [comment]
It is not obvious to me that these proposals provide for simpler and more legible configuration files than *just allowing newlines in inline tables*.

The entire problem with deeply nested tables is that they become unreadable and you lose your place and context for where you are. By adding placeholders and other sorts of references you still end up losing your place and context for where you are when the *number* of nested elements grows large rather than the *depth* grows.

A *mild* level of nesting has never, ever been a problem. If configs only ever needed something like a maximum of 4 to 6 levels of nesting, TOML would probably not be needed. The problem emerged due to deeply nested configurations. TOML resolves that by letting you point directly into a deep level. Adding light nesting returns the ability to have slightly more complex structures with additional context and the inline tables accomplish this for small numbers of elements. The problem comes when you have more than 3 or 4 elements in a small nested structure and it longer than is comfortable on a single line.

Fundamentally, this is always an issue of taste. There's not a consistent solution to this problem. So *just* let people make decisions based on taste and stop trying to square the circle. Automated tooling isn't ever going to be perfect, but being able to say something like "Drop into inline tables when there are fewer than M top level elements and nesting is no deeper than N levels" or "For Mi top level elements with no deeper than Ni levels do this. For Mj top level elements with no deeper than Nj levels do this" is better than what things end up looking like now when automated formatting spits something out.

**Comment by lmna** [comment]
Complexity of TOML language is at barely tolerable level. Adding even more syntactic features would ruin the objective of being obvious.

**Comment by nugend** [comment]
Then close the issue. The suggested syntax above in all the examples is novel and would lead extremely confusing large TOML documents.

**Comment by eksortso** [comment]
@lmna Our working definition of "obvious" is that you ought to be able to understand how TOML works with a single reading of the specification. This probably isn't the place to talk about that, aside from where table nesting is a factor. But I invite you to raise another issue, or start a discussion, to promote obviousness as you see it.

@nugend That suggested syntax is on #744. You can discuss it, or make a case to reject it, there. I think it could be useful, despite the additional considerations it would bring.

Please take a look at #525, and its followup PR #551, which I closed after almost a year's silence. I'm opposed to commas between KVPs except on single lines, but I thought that allowing newlines (and comments) as separators would work better at keeping inline tables in their place. What would you think of this?

**Comment by nugend** [comment]
I suspect they both stalled because they try to split the baby of "nesting can get too deep" vs "make nesting less painful"

The resistance to JSON-like syntax is non-obvious to me. JSON sucks for configuration because it's actually a serialization format for a very type poor language, you have to quote every key, and because deep nesting hurts and there's no escape hatch.

People *like* delimited, nested representations when they're not out of control because they visually indicate structure and because adjusting that visual representation is easy to do. All the the proposals that are not basically, "Fuck it, let's just do something that works kinda like JSON," don't actually serve the concern of visual structure _and_ easy adjustment.

Here's an example of what *I* would personally like to see.

```toml
[some_section]
api_params = {
   credential1 = "val1", credential2 = "val2", credential3 = "val3",
   connectionTimeout = 1, connectionRetries = 2, queryTimeout = 3, queryRetries =4,
   output_format = "HDF",
   }
```

BTW, I think trailing commas should be allowed too both within single line nested tables and multi-line nested tables should they be added.

If I adhere to #525/#551 and want to retain a visual indication of the related nature of the keys, that *has* to be this:

```toml
[some_section]
api_params ={
   credential1 = "val1"
   credential2 = "val2"
   credential3 = "val3"

   connectionTimeout =1
   connectionRetries = 2
   queryTimeout = 3
   queryRetries = 4

   output_format = "HDF"
   }
```

Which isn't actually better than the existing tables:

```toml
[some_section.api_params]
credential1 = "val1"
credential2 = "val2"
credential3 = "val3"

connectionTimeout =1
connectionRetries = 2
queryTimeout = 3
queryRetries = 4

output_format = "HDF"
```

Now what happens if we end up splitting api_params up because we start using some tool for secret management?

```toml
[some_section]
api_params = {
   connectionTimeout = 1, connectionRetries = 2, queryTimeout = 3, queryRetries =4,
   output_format = "HDF",
   }
secrets = {credential1 = "secret_reference1", credential2 = "secret_reference2", credential3 = "secret_reference3"}
```

In the other syntaxes:

```toml
[some_section]
api_params ={
   connectionTimeout =1
   connectionRetries = 2
   queryTimeout = 3
   queryRetries = 4

   output_format = "HDF"
   }
secrets = {credential1 = "secret_reference1", credential2 = "secret_reference2", credential3 = "secret_reference3"}
```

```toml
[some_section]
secrets = {credential1 = "secret_reference1", credential2 = "secret_reference2", credential3 = "secret_reference3"}

[some_section.api_params]
credential1 = "val1"
credential2 = "val2"
credential3 = "val3"

connectionTimeout =1
connectionRetries = 2
queryTimeout = 3
queryRetries = 4

output_format = "HDF"
```
Or if we want to stick to not using inline tables:

```toml
[some_section.api_params]
credential1 = "val1"
credential2 = "val2"
credential3 = "val3"

connectionTimeout =1
connectionRetries = 2
queryTimeout = 3
queryRetries = 4

output_format = "HDF"

[some_section.secrets]
credential1 = "secret_reference1"
credential2 = "secret_reference2"
credential3 = "secret_reference3"}
```

Those all have to change quite a bit more purely in terms of the character deltas

**Comment by pradyunsg** [comment]
@nugend None of those examples are something that we're designing for. Something like the following is *exactly* what I don't want to enable:

```toml
[some_section]
api_params = {
   connectionTimeout = 1, connectionRetries = 2, queryTimeout = 3, queryRetries =4,
   output_format = "HDF",
   }
secrets = {credential1 = "secret_reference1", credential2 = "secret_reference2", credential3 = "secret_reference3"}
```

As you noted, it can be broken out into:

```toml
[some_section.api_params]
credential1 = "val1"
credential2 = "val2"
credential3 = "val3"

connectionTimeout =1
connectionRetries = 2
queryTimeout = 3
queryRetries = 4

output_format = "HDF"

[some_section.secrets]
credential1 = "secret_reference1"
credential2 = "secret_reference2"
credential3 = "secret_reference3"
```

I find the latter much clearer, and I don't see what the advantage is to squashing something like this inline. The fact that TOML forces you to break up long inline tables into separate lines is good IMO -- it forces you to *not* jam everything on the same line.

**Comment by nugend** [comment]
Sorry, I didn't see a design document. Is it in another repository?

**Comment by pradyunsg** [comment]
@nugend what kind of design document are you thinking of?

**Comment by nugend** [comment]
One that outlines what the design goals for TOML are.

**Comment by pradyunsg** [comment]
Nothing like that exists. Between how this project is structured (BDFL-esque) and how the discussions take place, your best bet for figuring out the design approach here is to look at the issue tracker for what I or Tom have said.

**Comment by pradyunsg** [comment]
To me, the problem to solve here is that there's some cases where it's not possible to "nicely" spread the information. :)

```toml
dependencies = [
    "awesome-project",
    { git = "git@github.com:thatTiredPerson/importantButAbandonedProject", revision = "bae5084d627eb4cdabe07c1e743e3d97425d7f5c" },
    "my-awesome-documentation-thing",
]
```

```toml
[hello.deep.nested.context]
one = 1
two.three = 2.3
four = { five = 5, six = 6, seven = 7, eight = 8, nine = 9 }
```

I'm unconvinced right now about which approach is better here, or if we should just say "yea, that sort of complexity won't work".

**Comment by eksortso** [comment]
> To me, the problem to solve here is that there's some cases where it's not possible to "nicely" spread the information. :)

@pradyunsg The impetus behind #525/#551 was precisely to address the problem with the inline table in your first example. I was wanting to allow a variant of the following, and as things turn out, this particular approach would work well with small anonymous tables in the middle of arrays:

```toml
 # FYI, not valid as of v1.0.0
dependencies = [
    "awesome-project",
    {
        git = "git@github.com:thatTiredPerson/importantButAbandonedProject"
        revision = "bae5084d627eb4cdabe07c1e743e3d97425d7f5c"
    },
    "my-awesome-documentation-thing",
]
```

_[...]_
> I'm unconvinced right now about which approach is better here, or if we should just say "yea, that sort of complexity won't work".

I'm a little confused by what differentiates the two approaches you've presented. Could you state the same content in the two different styles, so we can compare apples to apples?

**Comment by pradyunsg** [comment]
The approaches I'm referring to leaning into the [table] syntax vs leaning into the inline table syntax.

I'm on mobile, so typing this out will take way longer than useful to type out the existing examples in those formats. 😅

---

FWIW, regarding #525, if we do go that route (I don't know yet), I think I'd prefer to enforce a "comma-followed-by-newline-for-all-keys" approach there, rather than newline is separator. That way, if you wanna break out your inline table across multiple lines, you don't need to remove the commas and only add additional newlines.

```toml
four = { five = 5, six = 6, seven = 7, eight = 8, nine = 9 }
# OR
four = {
   five = 5,
   six = 6,
   seven = 7,
   eight = 8,
   nine = 9,  # trailing comma is optional
}
```

```toml
# NOT THIS THO
four = {
    five = 5, six = 6, seven = 7,
    eight = 8, nine = 9
}
```

But yea, both of these feel more convoluted than "you can't do that, sorry". :(

**Comment by rezamahdi** [comment]
It seems with this approaches, TOML is becoming more close to Yaml.

I think allowing multi line tables, will fix many issues. In fact, a json
like syntax, without quote for keys...

**Comment by eksortso** [comment]
@pradyunsg Enforced style rules, I'm discovering, are inherently convoluted. But if something new for the standard would serve a good and valuable purpose, I'd rather have some way to do it, however ugly it is, than not have a way to do it. I'll concede on the commas thing.

(The ugliness could be a virtue in disguise, though. My cynical and provincial take is, "If it's too ugly for yinz to use, then maybe yinz oughta just do it the right way!" I have the exact same feeling about `NULL` values and not having `NULL` values in TOML.)

I'm sure the folks who pressed for inline tables in the first place felt the same internal conflicts as we're having here. I've not dived that deep into those past conversations.

@rezamahdi Close to YAML? Them's fighten' words! :) We need to hear this stuff sometimes though. It keeps us honest.

**Comment by rezamahdi** [comment]
😂
The fact is that TOML's destination never had to support 100-times depth or be a serialization format for complex hierarchy and objects. It is a simple configuration file format. But it had always been compared to Yaml....

**Comment by nugend** [comment]
> I have the exact same feeling about NULL values and not having NULL values in TOML

While it's great that TOML doesn't have an explicit null. Most programmatic handling of TOML has implicit nullity for all values outside of arrays. So, bit of a mixed bag there in a sense. Not that I think you _could_ do better without requiring a schema, which is not something I think would be universally workable for TOML. Ironically, the requirement of a schema makes null eminently tolerable as a syntactic convenience for expressing optional datatypes.

> "If it's too ugly for yinz to use, then maybe yinz oughta just do it the right way!"

This is the conundrum. TOML is the right and only way to do things in at least some cases as it's gotten standardization for various purposes (Rust Cargo, Python's new packaging files). But we all have differing opinions on what is ugly.

Personally, I feel that indenting TOML blocks beyond one level for array tables is fairly hideous and extremely hard to read. I don't *have* to though, since the spec doesn't require that. I don't know about anyone else, but my position could be boiled down to not *requiring* a certain syntax to express something by allowing for whitespace flexibility.

**Comment by brunoborges** [comment]
Regarding a schema, please visit https://github.com/brunoborges/toml-schema for a proposal.

**Comment by JeppeKlitgaard** [comment]
I am really impressed with TOML as a configuration language, but the lack of support for newlines in inline tables makes nested structures quite cumbersome in some cases.

I think the INI-style format is great in some or even most circumstances, but not in all circumstances. Presumably that is why inline tables were added in the first place. I think adding support for multiline 'inline tables' (or extended tables, extended inline tables, whatever the name given would be) is an obvious improvement to TOML and would not detract from the INI-style.

The only problem I see with it is that there are suddenly two valid ways of the same thing, which might lead to inconsistent use. This is however already the case for inline tables - sane people choose the appropriate one. The distinction between good and bad use of the extended inline table might be less clear, but I think people can be trusted to use the appropriate one.

The extended inline table is, in my opinion, sufficiently useful to warrant implementation even if it diverges slightly from the 'only  one obvious way' approach. TOML is a small, succinct language and the addition of extended inline tables will not change that.

I think requiring comma separation and allowing trailing commas would make it very clear that it is in fact just an inline table that stretches multiple lines - nothing more.  Allowing newline separation alone adds too much 'magic' to the language.

Further, I think something like

```toml
four = {
    five = 5, six = 6, seven = 7,
    eight = 8, nine = 9,
}
```

Should be supported. It might be slightly ugly, but if commas are to be the separator, it 'feels' like this should be a valid input. This again reduces 'magic' and puts an appropriate amount of styling responsibility on the user.

**Comment by mcarans** [comment]
@pradyunsg Yes! I would very much welcome a clearer way of nesting. I found it confusing to write the following to deal with "pages" and "children" for pydoc-markdown in toml and confess that I struggled to get the syntax right):

```toml
[tool.pydoc-markdown.renderer]
type = "mkdocs"

    [tool.pydoc-markdown.renderer.mkdocs_config]
    site_name = "HDX Python Scraper"

    [[tool.pydoc-markdown.renderer.pages]]
    title = "Home"

    [[tool.pydoc-markdown.renderer.pages]]
    title = "API Documentation"

        [[tool.pydoc-markdown.renderer.pages.children]]
        title = "Source Readers"
        contents = ["hdx.scraper.readers.*"]

        [[tool.pydoc-markdown.renderer.pages.children]]
        title = "Outputs"
        contents = ["hdx.scraper.jsonoutput.*", "hdx.scraper.googlesheets.*",
            "hdx.scraper.exceloutput.*"]
```

Look how much clearer this is in YAML:

```yaml
tool:
  pydoc-markdown:
    renderer:
      type: mkdocs
      mkdocs_config:
        site_name: HDX Python Scraper
      pages:
        - title: Home
        - title: API Documentation
          children:
            - title: Source Readers
              contents:
                - hdx.scraper.readers.*
            - title: Outputs
              contents:
                - hdx.scraper.jsonoutput.*
                - hdx.scraper.googlesheets.*
                - hdx.scraper.exceloutput.*
```

Nesting is one reason why developers of some commonly used libraries like asottile (author of flake8 and pre-commit) refuse to support pyproject.toml. For example [here](https://github.com/pre-commit/pre-commit/issues/1165#issuecomment-862603032), he says "you also don't actually want this, toml is really bad at representing nested structures" (and gives an example).

I think fixing nesting is important and likely to speed adoption of toml in general and pyproject.toml in particular.
