### ISSUE TITLE
How to specify array table under an array table?

### ISSUE THREAD

**Issue by vityafx** [toml-lang/toml#785]
I have an array of tables called `channels` and there I want to have an array of objects `queues`, so that it is an equivalent of json's:

```json
{
  "toml": {
    "channels": [
      {
        "name": "Channel #1",
        "queues": [
          {
            "name": "Queue #1"
          },
          {
            "name": "Queue #2"
          }
        ]
      },
      {
        "name": "Channel #2",
        "queues": [
          {
            "name": "Queue #3"
          },
          {
            "name": "Queue #4"
          }
        ]
      }
    ]
  }
}
```

Is it possible to do in toml?

All my attempts have been failing so far:

```toml
[[channels]]
name = "Channel 1"
queues = [[
    {
        name = "Queue 1"
    },
    {
        name = "Queue 2"
    },
]]
```

```toml
[[channels]]
name = "Channel 1"
queues = [
    {
        name = "Queue 1"
    },
    {
        name = "Queue 2"
    },
]
```
```toml
[[channels]]
name = "Channel 1"
[[queues]]
name = "Queue 1"
[[queues]]
name = "Queue 2"
```

I was trying to parse the toml tree using the rust's [`toml`](https://github.com/alexcrichton/toml-rs) crate.

**Comment by vityafx** [comment]
I sincerely and deeply apologise.

Just in the previous open issue https://github.com/toml-lang/toml/issues/782
There is an example, which works an I am using now:
```toml
[[channels]]
name = "Channel 1"
[[channels.queues]]
name = "Queue 1"
[[channels.queues]]
name = "Queue 2"
```
