### ISSUE TITLE
Release 1.0 final

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#788]
Since the last and final RC (rc.3) was released more than six ago and nothing important has come up since then, I'd say it's time to release TOML 1.0 final. There was only a clarification (regarding indentation) and an aesthetic fix (#784) needs to be merged before the next release.

So I'd say we don't need another RC in view of these minor changes, but can (after the merge) publish 1.0 final without further ado. Let's finish this this year!

**Comment by ChristianSi** [comment]
#769 is also still open, but as it wasn't addressed for RC.3 it doesn't look like it needs to be addressed for Final.

**Comment by eksortso** [comment]
I'm all for releasing v1.0.0 by the end of this year.

That said, I did want to include a note about the unnamed root table. It's come up a lot in discourse here, and I think it's important enough to allow for a clarification. Mind if I make a small PR?

**Comment by eksortso** [comment]
#769 fell off my radar. It ought to be addressed. The whole distinction between creating / defining / declaring tables is important enough to be included.

**Comment by eksortso** [comment]
PR #789 clarifies the status of the unnamed root table. Let me know what you think. I'll address #769 later today.

**Comment by genericptr** [comment]
Sorry if this is off-topic but I wanted to ask you guys. So, I've been using TOML for a month now and my only complaint is the restriction of new lines in inline tables. Arrays of tables are more cumbersome and have duplicate names (like target.bundle.resourcePaths_2 in this example) so tend to not use them. It's not a problem with these 2 keys but if the table gets longer then you really want some new lines to help format it.

Just curious why was this restriction imposed? Inline tables seem like a clearly better example of the new lines is kind of deal breaker unfortunately.

```toml
  target.bundle.resourcePaths_1 = [
    { source = "./Resources", destination = "${BUNDLE}/Contents/Resources" },
    { source = "./Resources", destination = "${BUNDLE}/Contents/Resources" }
  ]

[[target.bundle.resourcePaths_2]]

    source = "./Resources"
    destination = "${BUNDLE}/Contents/Resources"

[[target.bundle.resourcePaths_2]]

    source = "./Resources"
    destination = "${BUNDLE}/Contents/Resources"

```

**Comment by eksortso** [comment]
@genericptr TOML table sections came first, and were made to be similar to various INI formats. The array-of-tables notation was somewhat novel, but intuitively, it matched the single-bracket `[table]` notation well, and each instance of an `[[array]]`'s name indicated a new table in the array. Not too bad, but you do have to learn the double-bracket notation. It's not too cumbersome once you know where to use it.

Inline tables were introduced a few years later. They were never meant to replace the traditional tables. The intent was to offer an easy way to inject small, self-contained tables into a configuration. Making them single-line only was a deliberate design choice. We didn't want to make a JSON-like format. I initially railed against such an approach, but suggested a multi-line variant of the inline table when I realized that some tables do work better inside others. We found a better way of doing this, and I later [withdrew](https://github.com/toml-lang/toml/pull/551#issuecomment-500278810) my proposal. Probably for the best.

Since the elements of your table array are sufficiently big, I'll recommend that you stick with the table-array syntax. The duplication of names is a minor inconvenience, but you never lose your context. There is a proposal, #744, to shorten the length of those table names which has gotten some traction, but it's labeled for post-v1.0.0.

You can simplify what you've got by dropping the extra lines and indentation. Consider this variant of your second example. Is it more convenient?

```toml
[[target.bundle.resourcePaths_2]]
source = "./Resources"
destination = "${BUNDLE}/Contents/Resources"

[[target.bundle.resourcePaths_2]]
source = "./Resources"
destination = "${BUNDLE}/Contents/Resources"

[[target.bundle.resourcePaths_2]]
source = "./Resources"
destination = "${BUNDLE}/Contents/Resources"
```
