### ISSUE TITLE
Proposal: Template sub-keys with type hinting and validation

### ISSUE THREAD

**Issue by tysonclugg** [toml-lang/toml#791]
Taking a leaf from `make` where the `%` character is used in stem rules, I propose the following syntax:

```toml
[fruit.%.colour]
apple = "red"
banana = "yellow"
plum = "purple"
strawberry = "red"

[fruit.%.crunchy]
apple = true
banana = false
plum = 0
```

The `%` is used as a placeholder, each key expands using the section name as a template.  The resulting data structure would be as follows:

```python
{
    "fruit": {
        "apple": {"color": "red", "crunchy": True},
        "banana": {"color": "yellow", "crunchy": False},
        "plum": {"color": "purple", "crunchy": 0},
        "strawberry": {"color": "red"},
    },
}
```

The obvious advantage is that values of the same type are kept together with minimal verbosity.  Flow on advantages include:
- minimal diffs when adding, removing, or renaming sub-keys (eg: renaming `fruit.%.crunchy` to `fruit.%.isCrunchy`)
- impossible to miss renaming a sub-key for any given item
- ability to validate missing sub-keys: `WARNING: [fruit.%.crunchy] missing keys: strawberry`
- ability to validate inconsistent types: `WARNING: [fruit.%.crunchy] inconsistent types: boolean, integer`

The natural extension to this idea is providing type hints and stricter validation:

```toml
[fruit.%.crunchy:<boolean>]
apple = true
banana = false
plum = 0
strawberry = false
```
Parsing the above could result in `ERROR: [fruit.%.crunchy:<boolean>] type violations: plum`.

**Comment by eksortso** [comment]
A couple of things.

* This uses square brackets not as a table header, but as a way to define keys across multiple tables. It's an aspect-oriented approach to configuration. But the `%` in the middle of the meta-key's name is the only way to tell this header from a standard table header. You may want to consider a different bracket syntax for this concept.

* Although the intent is to ease the assignment of values to keys, this approach violates an important principle: that all of a table's keys are defined in exactly one region of the document (like inside an inline table's curly braces, or within a table section). If I wanted to add another fruit to this configuration, I would need to remember to update multiple template sections. That could be a deal-breaker.

* All syntaxes for TOML so far cross language barriers, more or less. But this proposes to use English type names for values whose types have thus far been inferred from their format.

* Type enforcement was removed from arrays not too long ago. Reintroducing type enforcement in this syntax would probably be a bad idea. Consistency in type can be manually distinguished by examining the values assigned all in one place. If there's a feature of the proposed syntax that offers a unique advantage over existing syntaxes, then this would certainly be it.

* For people who aren't familiar with the intricacies of `make` or templates, an equivalent in current TOML syntax would be appreciated, like this:

```toml
[fruit.apple]
colour = "red"
crunchy = true

[fruit.banana]
colour = "yellow"
crunchy = false

[fruit.plum]
colour = "purple"
crunchy = 0

[fruit.strawberry]
colour = "red"
```

Or more succinctly:
```toml
[fruit]
apple  = {colour="red",    crunchy=true}
banana = {colour="yellow", crunchy=false}
plum   = {colour="purple", crunchy=0}
strawberry = {colour="red"}
```
