### ISSUE TITLE
Raw strings (no escapes)

### ISSUE THREAD

**Issue by sorbits** [toml-lang/toml#80]
It’s not uncommon to need backslashes in configuration files (e.g. a regular expression).

I propose single-quoted strings be “raw strings” where backslash is always literal.

The only special character sequence inside raw strings should be the single quote, which, when followed by whitespace or newline, terminates the string, when followed by a second single quote, is literal (and the second single-quote is eaten). All other cases are invalid (although one could treat them as literal).

Example:

```
str = 'we can use '' inside raw strings' # single quotes in single quotes
regexp = '\b\d{1,3}(\.\d{1,3}){3}\b' # match IP address
```

**Comment by JakubKoralewski** [comment]
Hello time traveler here. I'd enjoy this feature as well.

**Comment by eksortso** [comment]
> Hello time traveler here. I'd enjoy this feature as well.

Which specific feature are you referring to? A way to include single quotes as literal characters?

We've had literal strings for years. And even though I've used them for regular expressions, I've been aware that they offer no way of escaping anything.

But, you can use triple single-quote delimiters. They allow single quotes, and they can also span multiple lines if you need them.

Here's how the old examples look, if written as multi-line literal strings:

```toml
# single quotes in triple quotes
str = '''we can use ' inside multi-like literal strings'''

# match IP address, using triple quotes
# (the first line break is ignored).
regexp = '''
\b\d{1,3}(\.\d{1,3}){3}\b'''
```
