### ISSUE TITLE
Proposal: Null type values for TOML

### ISSUE THREAD

**Issue by xcodz-dot** [toml-lang/toml#802]
Adding Null type values
Pro:
* Allows `null` or any other name for it to be used in such cases
  ```toml
  [[author]]
  email = null
  name = "Lorem Ipsum"
  bookname = "dolor sit amet"
  website = "https:///www.lipsum.com/"
  
  [[author]]
  email = "unknown@email.com"
  name = "Eiusmod Tempor"
  bookname = "Iusto Odio"
  website = null
  ```

Cons:
* it might not look so human freindly but `null` can be replaced as `none`, `nothing`, etc.
