### ISSUE TITLE
How do I come back to upper level after a table array

### ISSUE THREAD

**Issue by shallinta** [toml-lang/toml#814]
```toml
[[tables]]
name='name'
age=18
defaultAddress='home'
[[tables.address]]
tag='home'
pos='xxxx'
[[tables.address]]
tag='office'
pos='xxx'
```

will be parsed as json object:

```js
{
tables: [
  {
     name: 'name',
     age: 18,
     defaultAddress: 'home',
     address: [
       { tag: 'home', pos: 'xxxx' },
       { tag: 'office', pos: 'xxx' }
     ]
  }
]
}
```

this is no confusion.
but how should I do if I want the `defaultAddress` field to be placed after `address` array?
(I think it will be more logical and expected that default option appears after options array )

Or say, how to end a table array?
