### ISSUE TITLE
Ask how these json are converted toml

### ISSUE THREAD

**Issue by qcyblm** [toml-lang/toml#817]
module.exports = {
  head: [
    ['link', { rel: 'icon', href: '/logo.png' }]
  ]
}

**Comment by marzer** [comment]
```toml
[module.exports]
head = [
	['link', { rel = 'icon', href = '/logo.png' }]
]
```

**Comment by qcyblm** [comment]
![图片](https://user-images.githubusercontent.com/64412486/115200363-b7d5bf80-a126-11eb-8169-ab994abd14c9.png)

**Comment by marzer** [comment]
Arrays were homogeneous in earlier versions of toml, so it appears the VSCode plugin you're using is not up-to-date since it's expecting the array to only contain strings based on the type of the first element. You'd have to change the inner array to an inline table instead:

```toml
[module.exports]
head = [
	{ 'link' = { rel = 'icon', href = '/logo.png' } }
]
```
