### ISSUE TITLE
Tooling: Automate word wrapping

### ISSUE THREAD

**Issue by hukkin** [toml-lang/toml#841]
The Markdown spec seems to have lines wrapped at 80 characters. It's a bit tedious to do the wrapping manually when editing. It is possible to automate this with https://pre-commit.ci/ and [mdformat](https://github.com/executablebooks/mdformat) hook.

By adding a `.pre-commit-config.yaml`
```yaml
repos:
- repo: https://github.com/executablebooks/mdformat
  rev: '0.7.8'
  hooks:
  - id: mdformat
    args: ['--wrap=80', '--number']
```
and enabling pre-commit.ci we have a bot pushing correct word wrap changes to PRs. It is also [trivial](https://github.com/hukkin/mdformat-toc) to make this setup automatically fix the ToC if so desired.

I'll happily make a PR if this is something that maintainers want to see.

Disclaimer: I've developed mdformat
