### ISSUE TITLE
Does nesting inside Array of Tables necessarily results in ambiguous syntax?

### ISSUE THREAD

**Issue by abravalheri** [toml-lang/toml#856]
Hello, I have a doubt here regarding nesting "tables" or even "array of tables" inside array of tables...

I have the impression that the current syntax is ambiguous for that situation... Is that the case? (I would love to be wrong)

For example, if we consider the following example (in JSON):

```json
{
    "table": {
        "aot": [
            {"nested-table": {"nested_aot": [{"a": [0, 1]}, {"b": 2}, {"c": 3}]}},
            {"other-nested-table": {"d": 4, "e": 5, "f": [{"g": 6}]}}
        ]
    }
}
```

One could translate it to the following TOML:
```toml
[[table.aot]]
[[table.aot.nested-table.nested_aot]]
a = [0, 1]

[[table.aot.nested-table.nested_aot]]
b = 2

[[table.aot.nested-table.nested_aot]]
c = 3

[[table.aot.other-nested-table]]
d = 4
e = 5

[[table.aot.other-nested-table.f]]
g = 6
```

However this representation can be interpreted as if `"nested-table"` and `"other-nested-table"` were simply elements of the same `"[[table.aot]]"` item instead of belonging to 2 different items.

(Please notice that the first `[[table.aot]]` is required otherwise the TOML could be interpreted as if the value of `table.aot` was a single table containing the `"nested-table"` and `"other-nested-table"` keys).

NOTE: I understand that for the particular example, I could get around this limitation by using inline tables, however, on other data structures with more (or bigger) entries that is not ideal (and in some cases explicitly discouraged by the documentation).

**Comment by hukkin** [comment]
> However this representation can be interpreted as if "nested-table" and "other-nested-table" were simply elements of the same "[[table.aot]]" item instead of belonging to 2 different items.

The example TOML not only can but __*must*__ be interpreted in the way you mentioned.

For a TOML doc that translates to your JSON you will need to add an extra `[[table.aot]]` in order to create the second table in `table.aot`:
```toml
[[table.aot]]
[[table.aot.nested-table.nested_aot]]
a = [0, 1]

[[table.aot.nested-table.nested_aot]]
b = 2

[[table.aot.nested-table.nested_aot]]
c = 3

[[table.aot]]  # This is needed to create the second table in "table.aot"
[[table.aot.other-nested-table]]
d = 4
e = 5

[[table.aot.other-nested-table.f]]
g = 6
```
