### ISSUE TITLE
Assigning values via an array-of-tables like syntax

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#896]
[^gap]:  `# long gap` contains relevant configuration for each preceding

if i have 3 objects i can define them like this

```toml
[[long.path.to.array]]
value = 1
# long space defining stuff for preceding
[[long.path.to.array]]
value = 2
# long space defining stuff for preceding
[[long.path.to.array]]
value = 3
# long space defining stuff for preceding
```
which is good

also works well if the short thing works if `long.path.to.array` is a table

```toml
long.path.to.table.1 = 1
# long space defining stuff for preceding
long.path.to.table.2 = 2
# long space defining stuff for preceding
[long.path.to.table.3]
sometimes = 1
config = 2
is = 3
big = 4
# long space defining stuff for preceding
```

but if the thing i want to store is
```toml
long.path.to.array = [1, 2, { sometimes = 1, config = 2, is = 3, big = 4}]
```

their is no equivalent.

proposal is to support

```toml
[long.path.to.array]=1
# long gap
[long.path.to.array]=2
# long gap
[[long.path.to.array]]
sometimes = 1
config = 2
is = 3
big = 4
# long gap
```

this make mixed arrays a huge pain in 
for a lot of the configs I write at work, spacing out the assignment is important for readability's sake and just for symetry
and alt would be support assigning to empty

```toml
[[long.path.to.array]]
=1
# long space defining stuff for preceding
[[long.path.to.array]]
=2
# long space defining stuff for preceding
[[long.path.to.array]]
sometimes = 1
config = 2
is = 3
big = 4
# long space defining stuff for preceding
```

allowing assigment to empty is good becuse it means i can translate more json to toml
right now no way to support the json document
```json
"hello world"
```
