### ISSUE TITLE
remove newline and comma sensitivity

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#897]
make 
```toml
[thing1] a = 1 b = false c = 'stuff'
[thing2] a = 2
thing3 = { a = 3 b = 4 }
thing4 = {
    a = 4
}
```
valid toml
