### ISSUE TITLE
nesting proposal : allow full fledged toml to be nested inside inline tables

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#898]
```toml
creature.crow = {
    color = "black"
    [name]
        singular = "crow"
        plural = "crows"
        adjective = "crow"
    body_detail_plan = {
        standard_materials.remove_material = ['hair']
        [vertebrate_tissue_layers]
            skin = 'skin'
            fat = 'fat'
            muscle = 'muscle'
            bone = 'bone'
            cartilage = 'cartilage'
    }
}

variation.standard_quadruped_gaits = {
    args = ["walk", "trot" ]
    [cv_new_tag.gait.walk] = {
        [walk]
            full_speed = "!walk"
            no_build_up = true
            energy_use = 0
        [trot]
            full_speed = "!trot"
            energy_use = 0
            no_build_up = true
            layers_slow = true
            strength = true
            agility = true
            stealth_slows.percentage = 10
    }
}
```

pairs well with <https://github.com/toml-lang/toml/issues/897>

**Comment by pradyunsg** [comment]
Hi! Please see https://github.com/toml-lang/toml/issues/781 which discusses the broader topic here.

**Comment by lizelive** [comment]
#781 decided to go with "JSON-like"

#516 is an active discussion on how to do that by allowing newlines and trailing commas in inline tables

json is very nested. a value in json is also a valid json document. I like this cleanliness. it makes it easier to read + write json files.

This proposal makes toml tested like json by allowing values to be toml documents in their own right instead of restricting inline tables to very strict subset.

This means that toml documents should support

#516 as written requires a lot more characters and is harder to read

also is incontinent with the rest of toml on whether or not it requires a `,` after assignment because value is nested

you can compare 

```toml
creature.crow = {
    color = "black"
    [name]
        singular = "crow"
        plural = "crows"
        adjective = "crow"
    body_detail_plan = {
        standard_materials.remove_material = ['hair']
        [vertebrate_tissue_layers]
            skin = 'skin'
            fat = 'fat'
            muscle = 'muscle'
            bone = 'bone'
            cartilage = 'cartilage'
    }
}
```

```toml
creature.crow = {
    color = "black",
    name = {
        singular = "crow",
        plural = "crows",
        adjective = "crow",
    },
    body_detail_plan = {
        standard_materials = { remove_material = ['hair'] },
        vertebrate_tissue_layers = {
            skin = 'skin', 
            fat = 'fat',
            muscle = 'muscle',
            bone = 'bone',
            cartilage = 'cartilage',
        }
    }
}
```


1. easier to read
2. harder to make parse error (forgetting a `,` is an error)
3. it takes 235 chars vs 250 to represent the same thing cleaner
4. doesn't restrict user to bootleg yaml with `=` instead of `:` for some reason 
5. 6% more efficient
