### ISSUE TITLE
nesting proposal : push / pop

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#899]
<< pops to top level
trailing >> (or maybe . ) means strong and forces future tags to nest
leading . makes week and nests under last non-weak
[stuff] is defined in context

```toml
[<<creature.crow>>]
    color = "black"
    [name]
        singular = "crow"
        plural = "crows"
        adjective = "crow"
    [body_detail_plan]
    standard_materials.remove_material = ['hair']
        [.vertebrate_tissue_layers]
            skin = 'skin'
            fat = 'fat'
            muscle = 'muscle'
            bone = 'bone'
            cartilage = 'cartilage'
[<<variation.standard_quadruped_gaits>>]
    args = ["walk", "trot" ]
    [cv_new_tag.gait.walk.]
        [walk]
            full_speed = "!walk"
            [.no_build_up]
            energy_use = 0
        [trot]
            full_speed = "!trot"
            energy_use = 0
            [.no_build_up]
            [.layers_slow]
            [.strength]
            [.agility]
            [.stealth_slows]
                percentage = 10
```

can be awkward when you want to go up but not to topmos
could do it so matching number of `<` will bring you to `>` with same number
