### ISSUE TITLE
grammar confused?

### ISSUE THREAD

**Issue by 60ke** [toml-lang/toml#919]
```toml
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00
```
I noticed the key of `title` in the first line,but if i try put it in the end,like this:
```toml
[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

title = "TOML Example"
```
it's being the owner's key: `owner.title`,but that is not what I want，so i confused that  doese root's key(`title`)  must put in the head?
