### ISSUE TITLE
Support for indentation in inline tables

### ISSUE THREAD

**Issue by willpinha** [toml-lang/toml#920]
Is there a way to support indentation in inline tables? So instead of doing:

```toml
user = { name="abc", password = false }
```

We can do:

```toml
user = {
  name="abc",
  password = false
}
```

This is especially useful when we are dealing with many fields in the inline table.
