### ISSUE TITLE
TABLE: Current and previous block pointer

### ISSUE THREAD

**Issue by byehack** [toml-lang/toml#930]
This is basic idea, need to have more discussion.

## OLD
```toml
[[fruits]]
name = "apple"

[fruits.physical]  # subtable
color = "red"
shape = "round"

[[fruits.varieties]]  # nested array of tables
name = "red delicious"

[[fruits.varieties]]
name = "granny smith"


[[fruits]]
name = "banana"

[[fruits.varieties]]
name = "plantain"
```

## NEW
* `+` : Duplicating last table name.
* `^` : Goes back one block.
```toml
[[fruits]]
name = "apple"

[^.physical]  # subtable
color = "red"
shape = "round"

[[^.varieties]]  # nested array of tables
name = "red delicious"

[[+]]
name = "granny smith"


[[^]]
name = "banana"

[[^.varieties]]
name = "plantain"
```

## Json:
```json
{
  "fruits": [
    {
      "name": "apple",
      "physical": {
        "color": "red",
        "shape": "round"
      },
      "varieties": [
        { "name": "red delicious" },
        { "name": "granny smith" }
      ]
    },
    {
      "name": "banana",
      "varieties": [
        { "name": "plantain" }
      ]
    }
  ]
}
```
