### ISSUE TITLE
Naming conventions for arrays of tables

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#931]
Consider the following array of tables, using the "plural" naming convention that's commonly used [in the spec](https://toml.io/en/v1.0.0#array-of-tables):

```toml
[[planets]]
name = "Mercury"
aphelion = 0.466697
radius = 2440

[[planets]]
name = "Venus"
aphelion = 0.728213
radius = 6052

[[planets]]
name = "Earth"
aphelion = 0.9832899
radius = 6371

[[planets]]
name = "Mars"
aphelion = 1.66621
radius = 3390
```

While here is the same file in "singular" convention:

```toml
[[planet]]
name = "Mercury"
aphelion = 0.466697
radius = 2440

[[planet]]
name = "Venus"
aphelion = 0.728213
radius = 6052

[[planet]]
name = "Earth"
aphelion = 0.9832899
radius = 6371

[[planet]]
name = "Mars"
aphelion = 1.66621
radius = 3390
```

Everybody: which convention do you prefer? For me it's clear that I prefer the "singular" convention since array each element describes a single item. Hence it seems strange (for me) having a plural "section header" followed by a single item.

Therefore I consistently use the singular convention in my TOML files. I wonder how others here see this? Do you prefer singular or plural?

If many prefer singular, it might be worth considering switching to singular style for the examples used by the spec. Since though the spec doesn't give any explicit naming tips (and it shouldn't), many will tend to follow the example shown there.
