### ISSUE TITLE
u64: number too large to fit in target type

### ISSUE THREAD

**Issue by griffi-gh** [toml-lang/toml#964]
`u64` fields only accept numbers that can fit into `i64`

### Example 1

```toml
[world]
seed = 0xbeef_face_dead_cafe
```
```
thread 'main' panicked at 'Invalid configuration file: Error { inner: Error { inner: 
TomlError { message: "number too large to fit in target type", original: Some("[server]\naddress = \"0.0.0.0:12345\"\nmax_clients = 254\ntimeout_ms = 10000\n\n[world]\nseed = 0xaeef_face_dead_cafe\n"), keys: [], span: Some(88..89) } } }', kubi-server\src\config.rs:29:57
```

### Example 2 (works)

```toml
[world]
seed = 0x0eef_face_dead_cafe
```
