### ISSUE TITLE
[Feature Request] add `root` keyword for referring to the top-level object

### ISSUE THREAD

**Issue by alexmozaidze** [toml-lang/toml#984]
Allowing to refer to the top-level object as `root` would allow users to define a top-level array. In other words, it would be possible to turn this JSON:
```json
[
  { "name": "monky", "looks": "🐒" },
  { "name": "owl", "looks": "🦉" },
  { "name": "parrot", "looks": "🦜" }
]
```
Into the following TOML:
```toml
[[root]]
name = "monky"
looks = "🐒"

[[root]]
name = "owl"
looks = "🦉"

[[root]]
name = "parrot"
looks = "🦜"
```

Without changing anything on the backend.

It would also allow to define top-level parameters explicitly:

```toml
[root]
key = "value"
foo = "bar"
```

Though, I would discourage doing so.

## Possible problems

> What if someone decides it is a *great idea* to use both top-level parameters and `[[root]]`?

```toml
key = "value"

[[root]]
foo = "bar"
```

Simple, just error out. It doesn't make sense to have a value with 2 types at the same time.

---

> What about having both top-level parameters and `root` object?

```toml
key = "value"

[root]
foo = "bar"
```

Error out. Having parameters outside of any object *implies* `root`. So, basically, the above boils down to
```toml
[root]
key = "value"

[root]
foo = "bar"
```

And redefining an object is not allowed.

---

> `root` inside `root`

```toml
[root]
root = "haha, I made a paradox!"
```

Error out. `root` is reserved on top-level.

---

> Using `root` for creating new tables on the top-level.

```toml
key = "value"

[root.numbers]
one = 1
two = 2
```

Allowed, but discouraged.

---

> Using inline array syntax

```toml
root = [
  { name = "monky", looks = "🐒" },
  { name = "owl", looks = "🦉" },
  { name = "parrot", looks = "🦜" },
]
```

Error out, since `root` is reserved on top-level.

Perhaps, we could add the following syntax as an alternative?

```
[
  { name = "monky", looks = "🐒" },
  { name = "owl", looks = "🦉" },
  { name = "parrot", looks = "🦜" },
]
```

## How is this useful for configs?

Not much; configs don't need top-level arrays that often. This is mainly useful for when one uses TOML as a data file.

## Summary

Introducing `root` as a special object poses some potential problems with readability if the user decides to mix `root` with normal syntax, but it allows to create an array as the top-level structure (which is the only real benefit), making it possible to fully replace JSON with TOML.
